// Code generated by go-swagger; DO NOT EDIT.

package application_hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetReader is a Reader for the V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGet structure.
type V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewV2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewV2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewV2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewV2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetOK creates a V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetOK with default headers values
func NewV2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetOK() *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetOK {
	return &V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetOK{}
}

/*V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetOK handles this case with default header values.

OK
*/
type V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetOK struct {
	Payload *models.MetricParserResponse
}

func (o *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetOK) Error() string {
	return fmt.Sprintf("[GET /v2/applications/{application_id}/hosts/{host_id}/metrics.json][%d] v2ApplicationsHostsMetricsJsonByApplicationIdAndHostIdGetOK  %+v", 200, o.Payload)
}

func (o *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MetricParserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetUnauthorized creates a V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetUnauthorized with default headers values
func NewV2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetUnauthorized() *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetUnauthorized {
	return &V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetUnauthorized{}
}

/*V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetUnauthorized handles this case with default header values.

Invalid API key
*/
type V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetUnauthorized struct {
	Payload interface{}
}

func (o *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v2/applications/{application_id}/hosts/{host_id}/metrics.json][%d] v2ApplicationsHostsMetricsJsonByApplicationIdAndHostIdGetUnauthorized  %+v", 401, o.Payload)
}

func (o *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetForbidden creates a V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetForbidden with default headers values
func NewV2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetForbidden() *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetForbidden {
	return &V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetForbidden{}
}

/*V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetForbidden handles this case with default header values.

New Relic API access has not been enabled
*/
type V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetForbidden struct {
	Payload interface{}
}

func (o *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetForbidden) Error() string {
	return fmt.Sprintf("[GET /v2/applications/{application_id}/hosts/{host_id}/metrics.json][%d] v2ApplicationsHostsMetricsJsonByApplicationIdAndHostIdGetForbidden  %+v", 403, o.Payload)
}

func (o *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetDefault creates a V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetDefault with default headers values
func NewV2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetDefault(code int) *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetDefault {
	return &V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetDefault{
		_statusCode: code,
	}
}

/*V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetDefault handles this case with default header values.

A server error occurred, please contact <a href="http://support.newrelic.com">New Relic support</a>
*/
type V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the v2 applications hosts metrics Json by application Id and host Id get default response
func (o *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetDefault) Code() int {
	return o._statusCode
}

func (o *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetDefault) Error() string {
	return fmt.Sprintf("[GET /v2/applications/{application_id}/hosts/{host_id}/metrics.json][%d] V2ApplicationsHostsMetricsJsonByApplicationIdAndHostIdGet default  %+v", o._statusCode, o.Payload)
}

func (o *V2ApplicationsHostsMetricsJSONByApplicationIDAndHostIDGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
