// Code generated by go-swagger; DO NOT EDIT.

package application_hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewV2ApplicationsHostsJSONByApplicationIDAndIDGetParams creates a new V2ApplicationsHostsJSONByApplicationIDAndIDGetParams object
// with the default values initialized.
func NewV2ApplicationsHostsJSONByApplicationIDAndIDGetParams() *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams {
	var ()
	return &V2ApplicationsHostsJSONByApplicationIDAndIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2ApplicationsHostsJSONByApplicationIDAndIDGetParamsWithTimeout creates a new V2ApplicationsHostsJSONByApplicationIDAndIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2ApplicationsHostsJSONByApplicationIDAndIDGetParamsWithTimeout(timeout time.Duration) *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams {
	var ()
	return &V2ApplicationsHostsJSONByApplicationIDAndIDGetParams{

		timeout: timeout,
	}
}

// NewV2ApplicationsHostsJSONByApplicationIDAndIDGetParamsWithContext creates a new V2ApplicationsHostsJSONByApplicationIDAndIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2ApplicationsHostsJSONByApplicationIDAndIDGetParamsWithContext(ctx context.Context) *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams {
	var ()
	return &V2ApplicationsHostsJSONByApplicationIDAndIDGetParams{

		Context: ctx,
	}
}

// NewV2ApplicationsHostsJSONByApplicationIDAndIDGetParamsWithHTTPClient creates a new V2ApplicationsHostsJSONByApplicationIDAndIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2ApplicationsHostsJSONByApplicationIDAndIDGetParamsWithHTTPClient(client *http.Client) *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams {
	var ()
	return &V2ApplicationsHostsJSONByApplicationIDAndIDGetParams{
		HTTPClient: client,
	}
}

/*V2ApplicationsHostsJSONByApplicationIDAndIDGetParams contains all the parameters to send to the API endpoint
for the v2 applications hosts Json by application Id and Id get operation typically these are written to a http.Request
*/
type V2ApplicationsHostsJSONByApplicationIDAndIDGetParams struct {

	/*ApplicationID
	  Application ID

	*/
	ApplicationID int64
	/*HostID
	  Application host ID

	*/
	HostID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 applications hosts Json by application Id and Id get params
func (o *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams) WithTimeout(timeout time.Duration) *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 applications hosts Json by application Id and Id get params
func (o *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 applications hosts Json by application Id and Id get params
func (o *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams) WithContext(ctx context.Context) *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 applications hosts Json by application Id and Id get params
func (o *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 applications hosts Json by application Id and Id get params
func (o *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams) WithHTTPClient(client *http.Client) *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 applications hosts Json by application Id and Id get params
func (o *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplicationID adds the applicationID to the v2 applications hosts Json by application Id and Id get params
func (o *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams) WithApplicationID(applicationID int64) *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams {
	o.SetApplicationID(applicationID)
	return o
}

// SetApplicationID adds the applicationId to the v2 applications hosts Json by application Id and Id get params
func (o *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams) SetApplicationID(applicationID int64) {
	o.ApplicationID = applicationID
}

// WithHostID adds the hostID to the v2 applications hosts Json by application Id and Id get params
func (o *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams) WithHostID(hostID int64) *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams {
	o.SetHostID(hostID)
	return o
}

// SetHostID adds the hostId to the v2 applications hosts Json by application Id and Id get params
func (o *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams) SetHostID(hostID int64) {
	o.HostID = hostID
}

// WriteToRequest writes these params to a swagger request
func (o *V2ApplicationsHostsJSONByApplicationIDAndIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param application_id
	if err := r.SetPathParam("application_id", swag.FormatInt64(o.ApplicationID)); err != nil {
		return err
	}

	// path param host_id
	if err := r.SetPathParam("host_id", swag.FormatInt64(o.HostID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
