// Code generated by go-swagger; DO NOT EDIT.

package alerts_policy_channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// V2AlertsPolicyChannelsJSONPutReader is a Reader for the V2AlertsPolicyChannelsJSONPut structure.
type V2AlertsPolicyChannelsJSONPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2AlertsPolicyChannelsJSONPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewV2AlertsPolicyChannelsJSONPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewV2AlertsPolicyChannelsJSONPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewV2AlertsPolicyChannelsJSONPutForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewV2AlertsPolicyChannelsJSONPutNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewV2AlertsPolicyChannelsJSONPutUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewV2AlertsPolicyChannelsJSONPutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2AlertsPolicyChannelsJSONPutOK creates a V2AlertsPolicyChannelsJSONPutOK with default headers values
func NewV2AlertsPolicyChannelsJSONPutOK() *V2AlertsPolicyChannelsJSONPutOK {
	return &V2AlertsPolicyChannelsJSONPutOK{}
}

/*V2AlertsPolicyChannelsJSONPutOK handles this case with default header values.

OK
*/
type V2AlertsPolicyChannelsJSONPutOK struct {
	Payload *models.PolicyChannelsResponse
}

func (o *V2AlertsPolicyChannelsJSONPutOK) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_policy_channels.json][%d] v2AlertsPolicyChannelsJsonPutOK  %+v", 200, o.Payload)
}

func (o *V2AlertsPolicyChannelsJSONPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PolicyChannelsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsPolicyChannelsJSONPutUnauthorized creates a V2AlertsPolicyChannelsJSONPutUnauthorized with default headers values
func NewV2AlertsPolicyChannelsJSONPutUnauthorized() *V2AlertsPolicyChannelsJSONPutUnauthorized {
	return &V2AlertsPolicyChannelsJSONPutUnauthorized{}
}

/*V2AlertsPolicyChannelsJSONPutUnauthorized handles this case with default header values.

Invalid API key
*/
type V2AlertsPolicyChannelsJSONPutUnauthorized struct {
	Payload interface{}
}

func (o *V2AlertsPolicyChannelsJSONPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_policy_channels.json][%d] v2AlertsPolicyChannelsJsonPutUnauthorized  %+v", 401, o.Payload)
}

func (o *V2AlertsPolicyChannelsJSONPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsPolicyChannelsJSONPutForbidden creates a V2AlertsPolicyChannelsJSONPutForbidden with default headers values
func NewV2AlertsPolicyChannelsJSONPutForbidden() *V2AlertsPolicyChannelsJSONPutForbidden {
	return &V2AlertsPolicyChannelsJSONPutForbidden{}
}

/*V2AlertsPolicyChannelsJSONPutForbidden handles this case with default header values.

New Relic API access has not been enabled
*/
type V2AlertsPolicyChannelsJSONPutForbidden struct {
	Payload interface{}
}

func (o *V2AlertsPolicyChannelsJSONPutForbidden) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_policy_channels.json][%d] v2AlertsPolicyChannelsJsonPutForbidden  %+v", 403, o.Payload)
}

func (o *V2AlertsPolicyChannelsJSONPutForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsPolicyChannelsJSONPutNotFound creates a V2AlertsPolicyChannelsJSONPutNotFound with default headers values
func NewV2AlertsPolicyChannelsJSONPutNotFound() *V2AlertsPolicyChannelsJSONPutNotFound {
	return &V2AlertsPolicyChannelsJSONPutNotFound{}
}

/*V2AlertsPolicyChannelsJSONPutNotFound handles this case with default header values.

No policy channel found with the given ID
*/
type V2AlertsPolicyChannelsJSONPutNotFound struct {
	Payload interface{}
}

func (o *V2AlertsPolicyChannelsJSONPutNotFound) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_policy_channels.json][%d] v2AlertsPolicyChannelsJsonPutNotFound  %+v", 404, o.Payload)
}

func (o *V2AlertsPolicyChannelsJSONPutNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsPolicyChannelsJSONPutUnprocessableEntity creates a V2AlertsPolicyChannelsJSONPutUnprocessableEntity with default headers values
func NewV2AlertsPolicyChannelsJSONPutUnprocessableEntity() *V2AlertsPolicyChannelsJSONPutUnprocessableEntity {
	return &V2AlertsPolicyChannelsJSONPutUnprocessableEntity{}
}

/*V2AlertsPolicyChannelsJSONPutUnprocessableEntity handles this case with default header values.

Validation or internal error occurred while trying to update the policy channels
*/
type V2AlertsPolicyChannelsJSONPutUnprocessableEntity struct {
	Payload interface{}
}

func (o *V2AlertsPolicyChannelsJSONPutUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_policy_channels.json][%d] v2AlertsPolicyChannelsJsonPutUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *V2AlertsPolicyChannelsJSONPutUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsPolicyChannelsJSONPutDefault creates a V2AlertsPolicyChannelsJSONPutDefault with default headers values
func NewV2AlertsPolicyChannelsJSONPutDefault(code int) *V2AlertsPolicyChannelsJSONPutDefault {
	return &V2AlertsPolicyChannelsJSONPutDefault{
		_statusCode: code,
	}
}

/*V2AlertsPolicyChannelsJSONPutDefault handles this case with default header values.

A server error occurred, please contact <a href="http://support.newrelic.com">New Relic support</a>
*/
type V2AlertsPolicyChannelsJSONPutDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the v2 alerts policy channels Json put default response
func (o *V2AlertsPolicyChannelsJSONPutDefault) Code() int {
	return o._statusCode
}

func (o *V2AlertsPolicyChannelsJSONPutDefault) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_policy_channels.json][%d] V2AlertsPolicyChannelsJsonPut default  %+v", o._statusCode, o.Payload)
}

func (o *V2AlertsPolicyChannelsJSONPutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
