go_import_path: github.com/burck1/go-newrelic

language: go
go:
  - 1.8.1
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
    - os: osx
  fast_finish: true

before_install:
  - go get -v github.com/Masterminds/glide

install:
  - glide install

script:
  - go install
  - go test -v -cover $(glide novendor)

sudo: false
