// Code generated by go-swagger; DO NOT EDIT.

package dashboards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// NewV2DashboardsJSONByIDPutParams creates a new V2DashboardsJSONByIDPutParams object
// with the default values initialized.
func NewV2DashboardsJSONByIDPutParams() *V2DashboardsJSONByIDPutParams {
	var ()
	return &V2DashboardsJSONByIDPutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2DashboardsJSONByIDPutParamsWithTimeout creates a new V2DashboardsJSONByIDPutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2DashboardsJSONByIDPutParamsWithTimeout(timeout time.Duration) *V2DashboardsJSONByIDPutParams {
	var ()
	return &V2DashboardsJSONByIDPutParams{

		timeout: timeout,
	}
}

// NewV2DashboardsJSONByIDPutParamsWithContext creates a new V2DashboardsJSONByIDPutParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2DashboardsJSONByIDPutParamsWithContext(ctx context.Context) *V2DashboardsJSONByIDPutParams {
	var ()
	return &V2DashboardsJSONByIDPutParams{

		Context: ctx,
	}
}

// NewV2DashboardsJSONByIDPutParamsWithHTTPClient creates a new V2DashboardsJSONByIDPutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2DashboardsJSONByIDPutParamsWithHTTPClient(client *http.Client) *V2DashboardsJSONByIDPutParams {
	var ()
	return &V2DashboardsJSONByIDPutParams{
		HTTPClient: client,
	}
}

/*V2DashboardsJSONByIDPutParams contains all the parameters to send to the API endpoint
for the v2 dashboards Json by Id put operation typically these are written to a http.Request
*/
type V2DashboardsJSONByIDPutParams struct {

	/*Dashboard
	  Dashboard schema

	*/
	Dashboard *models.Dashboard
	/*DashboardID
	  Dashboard ID

	*/
	DashboardID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 dashboards Json by Id put params
func (o *V2DashboardsJSONByIDPutParams) WithTimeout(timeout time.Duration) *V2DashboardsJSONByIDPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 dashboards Json by Id put params
func (o *V2DashboardsJSONByIDPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 dashboards Json by Id put params
func (o *V2DashboardsJSONByIDPutParams) WithContext(ctx context.Context) *V2DashboardsJSONByIDPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 dashboards Json by Id put params
func (o *V2DashboardsJSONByIDPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 dashboards Json by Id put params
func (o *V2DashboardsJSONByIDPutParams) WithHTTPClient(client *http.Client) *V2DashboardsJSONByIDPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 dashboards Json by Id put params
func (o *V2DashboardsJSONByIDPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDashboard adds the dashboard to the v2 dashboards Json by Id put params
func (o *V2DashboardsJSONByIDPutParams) WithDashboard(dashboard *models.Dashboard) *V2DashboardsJSONByIDPutParams {
	o.SetDashboard(dashboard)
	return o
}

// SetDashboard adds the dashboard to the v2 dashboards Json by Id put params
func (o *V2DashboardsJSONByIDPutParams) SetDashboard(dashboard *models.Dashboard) {
	o.Dashboard = dashboard
}

// WithDashboardID adds the dashboardID to the v2 dashboards Json by Id put params
func (o *V2DashboardsJSONByIDPutParams) WithDashboardID(dashboardID int64) *V2DashboardsJSONByIDPutParams {
	o.SetDashboardID(dashboardID)
	return o
}

// SetDashboardID adds the dashboardId to the v2 dashboards Json by Id put params
func (o *V2DashboardsJSONByIDPutParams) SetDashboardID(dashboardID int64) {
	o.DashboardID = dashboardID
}

// WriteToRequest writes these params to a swagger request
func (o *V2DashboardsJSONByIDPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Dashboard != nil {
		if err := r.SetBodyParam(o.Dashboard); err != nil {
			return err
		}
	}

	// path param dashboard_id
	if err := r.SetPathParam("dashboard_id", swag.FormatInt64(o.DashboardID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
