// Code generated by go-swagger; DO NOT EDIT.

package application_deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewV2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams creates a new V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams object
// with the default values initialized.
func NewV2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams() *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams {
	var ()
	return &V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParamsWithTimeout creates a new V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParamsWithTimeout(timeout time.Duration) *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams {
	var ()
	return &V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams{

		timeout: timeout,
	}
}

// NewV2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParamsWithContext creates a new V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParamsWithContext(ctx context.Context) *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams {
	var ()
	return &V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams{

		Context: ctx,
	}
}

// NewV2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParamsWithHTTPClient creates a new V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParamsWithHTTPClient(client *http.Client) *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams {
	var ()
	return &V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams{
		HTTPClient: client,
	}
}

/*V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams contains all the parameters to send to the API endpoint
for the v2 applications deployments Json by application Id and Id delete operation typically these are written to a http.Request
*/
type V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams struct {

	/*ApplicationID
	  Application ID

	*/
	ApplicationID int64
	/*DeploymentID
	  Deployment ID

	*/
	DeploymentID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 applications deployments Json by application Id and Id delete params
func (o *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams) WithTimeout(timeout time.Duration) *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 applications deployments Json by application Id and Id delete params
func (o *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 applications deployments Json by application Id and Id delete params
func (o *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams) WithContext(ctx context.Context) *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 applications deployments Json by application Id and Id delete params
func (o *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 applications deployments Json by application Id and Id delete params
func (o *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams) WithHTTPClient(client *http.Client) *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 applications deployments Json by application Id and Id delete params
func (o *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplicationID adds the applicationID to the v2 applications deployments Json by application Id and Id delete params
func (o *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams) WithApplicationID(applicationID int64) *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams {
	o.SetApplicationID(applicationID)
	return o
}

// SetApplicationID adds the applicationId to the v2 applications deployments Json by application Id and Id delete params
func (o *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams) SetApplicationID(applicationID int64) {
	o.ApplicationID = applicationID
}

// WithDeploymentID adds the deploymentID to the v2 applications deployments Json by application Id and Id delete params
func (o *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams) WithDeploymentID(deploymentID int64) *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams {
	o.SetDeploymentID(deploymentID)
	return o
}

// SetDeploymentID adds the deploymentId to the v2 applications deployments Json by application Id and Id delete params
func (o *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams) SetDeploymentID(deploymentID int64) {
	o.DeploymentID = deploymentID
}

// WriteToRequest writes these params to a swagger request
func (o *V2ApplicationsDeploymentsJSONByApplicationIDAndIDDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param application_id
	if err := r.SetPathParam("application_id", swag.FormatInt64(o.ApplicationID)); err != nil {
		return err
	}

	// path param deployment_id
	if err := r.SetPathParam("deployment_id", swag.FormatInt64(o.DeploymentID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
