// Code generated by go-swagger; DO NOT EDIT.

package alerts_conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// NewV2AlertsConditionsPoliciesJSONByPolicyIDPostParams creates a new V2AlertsConditionsPoliciesJSONByPolicyIDPostParams object
// with the default values initialized.
func NewV2AlertsConditionsPoliciesJSONByPolicyIDPostParams() *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams {
	var ()
	return &V2AlertsConditionsPoliciesJSONByPolicyIDPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2AlertsConditionsPoliciesJSONByPolicyIDPostParamsWithTimeout creates a new V2AlertsConditionsPoliciesJSONByPolicyIDPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2AlertsConditionsPoliciesJSONByPolicyIDPostParamsWithTimeout(timeout time.Duration) *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams {
	var ()
	return &V2AlertsConditionsPoliciesJSONByPolicyIDPostParams{

		timeout: timeout,
	}
}

// NewV2AlertsConditionsPoliciesJSONByPolicyIDPostParamsWithContext creates a new V2AlertsConditionsPoliciesJSONByPolicyIDPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2AlertsConditionsPoliciesJSONByPolicyIDPostParamsWithContext(ctx context.Context) *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams {
	var ()
	return &V2AlertsConditionsPoliciesJSONByPolicyIDPostParams{

		Context: ctx,
	}
}

// NewV2AlertsConditionsPoliciesJSONByPolicyIDPostParamsWithHTTPClient creates a new V2AlertsConditionsPoliciesJSONByPolicyIDPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2AlertsConditionsPoliciesJSONByPolicyIDPostParamsWithHTTPClient(client *http.Client) *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams {
	var ()
	return &V2AlertsConditionsPoliciesJSONByPolicyIDPostParams{
		HTTPClient: client,
	}
}

/*V2AlertsConditionsPoliciesJSONByPolicyIDPostParams contains all the parameters to send to the API endpoint
for the v2 alerts conditions policies Json by policy Id post operation typically these are written to a http.Request
*/
type V2AlertsConditionsPoliciesJSONByPolicyIDPostParams struct {

	/*Condition
	  Condition schema

	*/
	Condition *models.Condition
	/*PolicyID
	  Alerts policy ID

	*/
	PolicyID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 alerts conditions policies Json by policy Id post params
func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams) WithTimeout(timeout time.Duration) *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 alerts conditions policies Json by policy Id post params
func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 alerts conditions policies Json by policy Id post params
func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams) WithContext(ctx context.Context) *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 alerts conditions policies Json by policy Id post params
func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 alerts conditions policies Json by policy Id post params
func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams) WithHTTPClient(client *http.Client) *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 alerts conditions policies Json by policy Id post params
func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCondition adds the condition to the v2 alerts conditions policies Json by policy Id post params
func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams) WithCondition(condition *models.Condition) *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams {
	o.SetCondition(condition)
	return o
}

// SetCondition adds the condition to the v2 alerts conditions policies Json by policy Id post params
func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams) SetCondition(condition *models.Condition) {
	o.Condition = condition
}

// WithPolicyID adds the policyID to the v2 alerts conditions policies Json by policy Id post params
func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams) WithPolicyID(policyID int64) *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams {
	o.SetPolicyID(policyID)
	return o
}

// SetPolicyID adds the policyId to the v2 alerts conditions policies Json by policy Id post params
func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams) SetPolicyID(policyID int64) {
	o.PolicyID = policyID
}

// WriteToRequest writes these params to a swagger request
func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Condition != nil {
		if err := r.SetBodyParam(o.Condition); err != nil {
			return err
		}
	}

	// path param policy_id
	if err := r.SetPathParam("policy_id", swag.FormatInt64(o.PolicyID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
