// Code generated by go-swagger; DO NOT EDIT.

package alerts_conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// NewV2AlertsConditionsJSONByIDPutParams creates a new V2AlertsConditionsJSONByIDPutParams object
// with the default values initialized.
func NewV2AlertsConditionsJSONByIDPutParams() *V2AlertsConditionsJSONByIDPutParams {
	var ()
	return &V2AlertsConditionsJSONByIDPutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2AlertsConditionsJSONByIDPutParamsWithTimeout creates a new V2AlertsConditionsJSONByIDPutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2AlertsConditionsJSONByIDPutParamsWithTimeout(timeout time.Duration) *V2AlertsConditionsJSONByIDPutParams {
	var ()
	return &V2AlertsConditionsJSONByIDPutParams{

		timeout: timeout,
	}
}

// NewV2AlertsConditionsJSONByIDPutParamsWithContext creates a new V2AlertsConditionsJSONByIDPutParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2AlertsConditionsJSONByIDPutParamsWithContext(ctx context.Context) *V2AlertsConditionsJSONByIDPutParams {
	var ()
	return &V2AlertsConditionsJSONByIDPutParams{

		Context: ctx,
	}
}

// NewV2AlertsConditionsJSONByIDPutParamsWithHTTPClient creates a new V2AlertsConditionsJSONByIDPutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2AlertsConditionsJSONByIDPutParamsWithHTTPClient(client *http.Client) *V2AlertsConditionsJSONByIDPutParams {
	var ()
	return &V2AlertsConditionsJSONByIDPutParams{
		HTTPClient: client,
	}
}

/*V2AlertsConditionsJSONByIDPutParams contains all the parameters to send to the API endpoint
for the v2 alerts conditions Json by Id put operation typically these are written to a http.Request
*/
type V2AlertsConditionsJSONByIDPutParams struct {

	/*Condition
	  Condition schema

	*/
	Condition *models.Condition
	/*ConditionID
	  Alerts condition ID to update

	*/
	ConditionID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 alerts conditions Json by Id put params
func (o *V2AlertsConditionsJSONByIDPutParams) WithTimeout(timeout time.Duration) *V2AlertsConditionsJSONByIDPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 alerts conditions Json by Id put params
func (o *V2AlertsConditionsJSONByIDPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 alerts conditions Json by Id put params
func (o *V2AlertsConditionsJSONByIDPutParams) WithContext(ctx context.Context) *V2AlertsConditionsJSONByIDPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 alerts conditions Json by Id put params
func (o *V2AlertsConditionsJSONByIDPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 alerts conditions Json by Id put params
func (o *V2AlertsConditionsJSONByIDPutParams) WithHTTPClient(client *http.Client) *V2AlertsConditionsJSONByIDPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 alerts conditions Json by Id put params
func (o *V2AlertsConditionsJSONByIDPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCondition adds the condition to the v2 alerts conditions Json by Id put params
func (o *V2AlertsConditionsJSONByIDPutParams) WithCondition(condition *models.Condition) *V2AlertsConditionsJSONByIDPutParams {
	o.SetCondition(condition)
	return o
}

// SetCondition adds the condition to the v2 alerts conditions Json by Id put params
func (o *V2AlertsConditionsJSONByIDPutParams) SetCondition(condition *models.Condition) {
	o.Condition = condition
}

// WithConditionID adds the conditionID to the v2 alerts conditions Json by Id put params
func (o *V2AlertsConditionsJSONByIDPutParams) WithConditionID(conditionID int64) *V2AlertsConditionsJSONByIDPutParams {
	o.SetConditionID(conditionID)
	return o
}

// SetConditionID adds the conditionId to the v2 alerts conditions Json by Id put params
func (o *V2AlertsConditionsJSONByIDPutParams) SetConditionID(conditionID int64) {
	o.ConditionID = conditionID
}

// WriteToRequest writes these params to a swagger request
func (o *V2AlertsConditionsJSONByIDPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Condition != nil {
		if err := r.SetBodyParam(o.Condition); err != nil {
			return err
		}
	}

	// path param condition_id
	if err := r.SetPathParam("condition_id", swag.FormatInt64(o.ConditionID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
