// Code generated by go-swagger; DO NOT EDIT.

package alerts_conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// V2AlertsConditionsPoliciesJSONByPolicyIDPostReader is a Reader for the V2AlertsConditionsPoliciesJSONByPolicyIDPost structure.
type V2AlertsConditionsPoliciesJSONByPolicyIDPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewV2AlertsConditionsPoliciesJSONByPolicyIDPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewV2AlertsConditionsPoliciesJSONByPolicyIDPostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewV2AlertsConditionsPoliciesJSONByPolicyIDPostForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewV2AlertsConditionsPoliciesJSONByPolicyIDPostNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewV2AlertsConditionsPoliciesJSONByPolicyIDPostUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewV2AlertsConditionsPoliciesJSONByPolicyIDPostDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2AlertsConditionsPoliciesJSONByPolicyIDPostOK creates a V2AlertsConditionsPoliciesJSONByPolicyIDPostOK with default headers values
func NewV2AlertsConditionsPoliciesJSONByPolicyIDPostOK() *V2AlertsConditionsPoliciesJSONByPolicyIDPostOK {
	return &V2AlertsConditionsPoliciesJSONByPolicyIDPostOK{}
}

/*V2AlertsConditionsPoliciesJSONByPolicyIDPostOK handles this case with default header values.

OK
*/
type V2AlertsConditionsPoliciesJSONByPolicyIDPostOK struct {
	Payload *models.ConditionResponse
}

func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostOK) Error() string {
	return fmt.Sprintf("[POST /v2/alerts_conditions/policies/{policy_id}.json][%d] v2AlertsConditionsPoliciesJsonByPolicyIdPostOK  %+v", 200, o.Payload)
}

func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConditionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsConditionsPoliciesJSONByPolicyIDPostUnauthorized creates a V2AlertsConditionsPoliciesJSONByPolicyIDPostUnauthorized with default headers values
func NewV2AlertsConditionsPoliciesJSONByPolicyIDPostUnauthorized() *V2AlertsConditionsPoliciesJSONByPolicyIDPostUnauthorized {
	return &V2AlertsConditionsPoliciesJSONByPolicyIDPostUnauthorized{}
}

/*V2AlertsConditionsPoliciesJSONByPolicyIDPostUnauthorized handles this case with default header values.

Invalid API key
*/
type V2AlertsConditionsPoliciesJSONByPolicyIDPostUnauthorized struct {
	Payload interface{}
}

func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v2/alerts_conditions/policies/{policy_id}.json][%d] v2AlertsConditionsPoliciesJsonByPolicyIdPostUnauthorized  %+v", 401, o.Payload)
}

func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsConditionsPoliciesJSONByPolicyIDPostForbidden creates a V2AlertsConditionsPoliciesJSONByPolicyIDPostForbidden with default headers values
func NewV2AlertsConditionsPoliciesJSONByPolicyIDPostForbidden() *V2AlertsConditionsPoliciesJSONByPolicyIDPostForbidden {
	return &V2AlertsConditionsPoliciesJSONByPolicyIDPostForbidden{}
}

/*V2AlertsConditionsPoliciesJSONByPolicyIDPostForbidden handles this case with default header values.

New Relic API access has not been enabled
*/
type V2AlertsConditionsPoliciesJSONByPolicyIDPostForbidden struct {
	Payload interface{}
}

func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostForbidden) Error() string {
	return fmt.Sprintf("[POST /v2/alerts_conditions/policies/{policy_id}.json][%d] v2AlertsConditionsPoliciesJsonByPolicyIdPostForbidden  %+v", 403, o.Payload)
}

func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsConditionsPoliciesJSONByPolicyIDPostNotFound creates a V2AlertsConditionsPoliciesJSONByPolicyIDPostNotFound with default headers values
func NewV2AlertsConditionsPoliciesJSONByPolicyIDPostNotFound() *V2AlertsConditionsPoliciesJSONByPolicyIDPostNotFound {
	return &V2AlertsConditionsPoliciesJSONByPolicyIDPostNotFound{}
}

/*V2AlertsConditionsPoliciesJSONByPolicyIDPostNotFound handles this case with default header values.

No alert policy was found with the given ID
*/
type V2AlertsConditionsPoliciesJSONByPolicyIDPostNotFound struct {
	Payload interface{}
}

func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostNotFound) Error() string {
	return fmt.Sprintf("[POST /v2/alerts_conditions/policies/{policy_id}.json][%d] v2AlertsConditionsPoliciesJsonByPolicyIdPostNotFound  %+v", 404, o.Payload)
}

func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsConditionsPoliciesJSONByPolicyIDPostUnprocessableEntity creates a V2AlertsConditionsPoliciesJSONByPolicyIDPostUnprocessableEntity with default headers values
func NewV2AlertsConditionsPoliciesJSONByPolicyIDPostUnprocessableEntity() *V2AlertsConditionsPoliciesJSONByPolicyIDPostUnprocessableEntity {
	return &V2AlertsConditionsPoliciesJSONByPolicyIDPostUnprocessableEntity{}
}

/*V2AlertsConditionsPoliciesJSONByPolicyIDPostUnprocessableEntity handles this case with default header values.

Validation error occurred while trying to create the alert condition
*/
type V2AlertsConditionsPoliciesJSONByPolicyIDPostUnprocessableEntity struct {
	Payload interface{}
}

func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /v2/alerts_conditions/policies/{policy_id}.json][%d] v2AlertsConditionsPoliciesJsonByPolicyIdPostUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsConditionsPoliciesJSONByPolicyIDPostDefault creates a V2AlertsConditionsPoliciesJSONByPolicyIDPostDefault with default headers values
func NewV2AlertsConditionsPoliciesJSONByPolicyIDPostDefault(code int) *V2AlertsConditionsPoliciesJSONByPolicyIDPostDefault {
	return &V2AlertsConditionsPoliciesJSONByPolicyIDPostDefault{
		_statusCode: code,
	}
}

/*V2AlertsConditionsPoliciesJSONByPolicyIDPostDefault handles this case with default header values.

A server error occurred, please contact <a href="http://support.newrelic.com">New Relic support</a>
*/
type V2AlertsConditionsPoliciesJSONByPolicyIDPostDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the v2 alerts conditions policies Json by policy Id post default response
func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostDefault) Code() int {
	return o._statusCode
}

func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostDefault) Error() string {
	return fmt.Sprintf("[POST /v2/alerts_conditions/policies/{policy_id}.json][%d] V2AlertsConditionsPoliciesJsonByPolicyIdPost default  %+v", o._statusCode, o.Payload)
}

func (o *V2AlertsConditionsPoliciesJSONByPolicyIDPostDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
