// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewV2ApplicationsJSONByIDGetParams creates a new V2ApplicationsJSONByIDGetParams object
// with the default values initialized.
func NewV2ApplicationsJSONByIDGetParams() *V2ApplicationsJSONByIDGetParams {
	var ()
	return &V2ApplicationsJSONByIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2ApplicationsJSONByIDGetParamsWithTimeout creates a new V2ApplicationsJSONByIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2ApplicationsJSONByIDGetParamsWithTimeout(timeout time.Duration) *V2ApplicationsJSONByIDGetParams {
	var ()
	return &V2ApplicationsJSONByIDGetParams{

		timeout: timeout,
	}
}

// NewV2ApplicationsJSONByIDGetParamsWithContext creates a new V2ApplicationsJSONByIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2ApplicationsJSONByIDGetParamsWithContext(ctx context.Context) *V2ApplicationsJSONByIDGetParams {
	var ()
	return &V2ApplicationsJSONByIDGetParams{

		Context: ctx,
	}
}

// NewV2ApplicationsJSONByIDGetParamsWithHTTPClient creates a new V2ApplicationsJSONByIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2ApplicationsJSONByIDGetParamsWithHTTPClient(client *http.Client) *V2ApplicationsJSONByIDGetParams {
	var ()
	return &V2ApplicationsJSONByIDGetParams{
		HTTPClient: client,
	}
}

/*V2ApplicationsJSONByIDGetParams contains all the parameters to send to the API endpoint
for the v2 applications Json by Id get operation typically these are written to a http.Request
*/
type V2ApplicationsJSONByIDGetParams struct {

	/*ApplicationID
	  Application ID

	*/
	ApplicationID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 applications Json by Id get params
func (o *V2ApplicationsJSONByIDGetParams) WithTimeout(timeout time.Duration) *V2ApplicationsJSONByIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 applications Json by Id get params
func (o *V2ApplicationsJSONByIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 applications Json by Id get params
func (o *V2ApplicationsJSONByIDGetParams) WithContext(ctx context.Context) *V2ApplicationsJSONByIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 applications Json by Id get params
func (o *V2ApplicationsJSONByIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 applications Json by Id get params
func (o *V2ApplicationsJSONByIDGetParams) WithHTTPClient(client *http.Client) *V2ApplicationsJSONByIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 applications Json by Id get params
func (o *V2ApplicationsJSONByIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplicationID adds the applicationID to the v2 applications Json by Id get params
func (o *V2ApplicationsJSONByIDGetParams) WithApplicationID(applicationID int64) *V2ApplicationsJSONByIDGetParams {
	o.SetApplicationID(applicationID)
	return o
}

// SetApplicationID adds the applicationId to the v2 applications Json by Id get params
func (o *V2ApplicationsJSONByIDGetParams) SetApplicationID(applicationID int64) {
	o.ApplicationID = applicationID
}

// WriteToRequest writes these params to a swagger request
func (o *V2ApplicationsJSONByIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param application_id
	if err := r.SetPathParam("application_id", swag.FormatInt64(o.ApplicationID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
