// Code generated by go-swagger; DO NOT EDIT.

package usages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// V2UsagesJSONByProductGetReader is a Reader for the V2UsagesJSONByProductGet structure.
type V2UsagesJSONByProductGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2UsagesJSONByProductGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewV2UsagesJSONByProductGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewV2UsagesJSONByProductGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewV2UsagesJSONByProductGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewV2UsagesJSONByProductGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2UsagesJSONByProductGetOK creates a V2UsagesJSONByProductGetOK with default headers values
func NewV2UsagesJSONByProductGetOK() *V2UsagesJSONByProductGetOK {
	return &V2UsagesJSONByProductGetOK{}
}

/*V2UsagesJSONByProductGetOK handles this case with default header values.

OK
*/
type V2UsagesJSONByProductGetOK struct {
	Payload *models.UsageDataResponse
}

func (o *V2UsagesJSONByProductGetOK) Error() string {
	return fmt.Sprintf("[GET /v2/usages/{product}.json][%d] v2UsagesJsonByProductGetOK  %+v", 200, o.Payload)
}

func (o *V2UsagesJSONByProductGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UsageDataResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UsagesJSONByProductGetUnauthorized creates a V2UsagesJSONByProductGetUnauthorized with default headers values
func NewV2UsagesJSONByProductGetUnauthorized() *V2UsagesJSONByProductGetUnauthorized {
	return &V2UsagesJSONByProductGetUnauthorized{}
}

/*V2UsagesJSONByProductGetUnauthorized handles this case with default header values.

Invalid API key
*/
type V2UsagesJSONByProductGetUnauthorized struct {
	Payload interface{}
}

func (o *V2UsagesJSONByProductGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v2/usages/{product}.json][%d] v2UsagesJsonByProductGetUnauthorized  %+v", 401, o.Payload)
}

func (o *V2UsagesJSONByProductGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UsagesJSONByProductGetForbidden creates a V2UsagesJSONByProductGetForbidden with default headers values
func NewV2UsagesJSONByProductGetForbidden() *V2UsagesJSONByProductGetForbidden {
	return &V2UsagesJSONByProductGetForbidden{}
}

/*V2UsagesJSONByProductGetForbidden handles this case with default header values.

New Relic API access has not been enabled
*/
type V2UsagesJSONByProductGetForbidden struct {
	Payload interface{}
}

func (o *V2UsagesJSONByProductGetForbidden) Error() string {
	return fmt.Sprintf("[GET /v2/usages/{product}.json][%d] v2UsagesJsonByProductGetForbidden  %+v", 403, o.Payload)
}

func (o *V2UsagesJSONByProductGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UsagesJSONByProductGetDefault creates a V2UsagesJSONByProductGetDefault with default headers values
func NewV2UsagesJSONByProductGetDefault(code int) *V2UsagesJSONByProductGetDefault {
	return &V2UsagesJSONByProductGetDefault{
		_statusCode: code,
	}
}

/*V2UsagesJSONByProductGetDefault handles this case with default header values.

A server error occurred, please contact <a href="http://support.newrelic.com">New Relic support</a>
*/
type V2UsagesJSONByProductGetDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the v2 usages Json by product get default response
func (o *V2UsagesJSONByProductGetDefault) Code() int {
	return o._statusCode
}

func (o *V2UsagesJSONByProductGetDefault) Error() string {
	return fmt.Sprintf("[GET /v2/usages/{product}.json][%d] V2UsagesJsonByProductGet default  %+v", o._statusCode, o.Payload)
}

func (o *V2UsagesJSONByProductGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
