// Code generated by go-swagger; DO NOT EDIT.

package alerts_synthetics_conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// NewV2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams creates a new V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams object
// with the default values initialized.
func NewV2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams() *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams {
	var ()
	return &V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParamsWithTimeout creates a new V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParamsWithTimeout(timeout time.Duration) *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams {
	var ()
	return &V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams{

		timeout: timeout,
	}
}

// NewV2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParamsWithContext creates a new V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParamsWithContext(ctx context.Context) *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams {
	var ()
	return &V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams{

		Context: ctx,
	}
}

// NewV2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParamsWithHTTPClient creates a new V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParamsWithHTTPClient(client *http.Client) *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams {
	var ()
	return &V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams{
		HTTPClient: client,
	}
}

/*V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams contains all the parameters to send to the API endpoint
for the v2 alerts synthetics conditions policies Json by policy Id post operation typically these are written to a http.Request
*/
type V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams struct {

	/*PolicyID
	  Alerts policy ID

	*/
	PolicyID int64
	/*SyntheticsCondition
	  Condition schema

	*/
	SyntheticsCondition *models.SyntheticsCondition

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 alerts synthetics conditions policies Json by policy Id post params
func (o *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams) WithTimeout(timeout time.Duration) *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 alerts synthetics conditions policies Json by policy Id post params
func (o *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 alerts synthetics conditions policies Json by policy Id post params
func (o *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams) WithContext(ctx context.Context) *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 alerts synthetics conditions policies Json by policy Id post params
func (o *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 alerts synthetics conditions policies Json by policy Id post params
func (o *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams) WithHTTPClient(client *http.Client) *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 alerts synthetics conditions policies Json by policy Id post params
func (o *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPolicyID adds the policyID to the v2 alerts synthetics conditions policies Json by policy Id post params
func (o *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams) WithPolicyID(policyID int64) *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams {
	o.SetPolicyID(policyID)
	return o
}

// SetPolicyID adds the policyId to the v2 alerts synthetics conditions policies Json by policy Id post params
func (o *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams) SetPolicyID(policyID int64) {
	o.PolicyID = policyID
}

// WithSyntheticsCondition adds the syntheticsCondition to the v2 alerts synthetics conditions policies Json by policy Id post params
func (o *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams) WithSyntheticsCondition(syntheticsCondition *models.SyntheticsCondition) *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams {
	o.SetSyntheticsCondition(syntheticsCondition)
	return o
}

// SetSyntheticsCondition adds the syntheticsCondition to the v2 alerts synthetics conditions policies Json by policy Id post params
func (o *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams) SetSyntheticsCondition(syntheticsCondition *models.SyntheticsCondition) {
	o.SyntheticsCondition = syntheticsCondition
}

// WriteToRequest writes these params to a swagger request
func (o *V2AlertsSyntheticsConditionsPoliciesJSONByPolicyIDPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param policy_id
	if err := r.SetPathParam("policy_id", swag.FormatInt64(o.PolicyID)); err != nil {
		return err
	}

	if o.SyntheticsCondition != nil {
		if err := r.SetBodyParam(o.SyntheticsCondition); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
