// Code generated by go-swagger; DO NOT EDIT.

package mobile_applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// V2MobileApplicationsMetricsJSONByMobileApplicationIDGetReader is a Reader for the V2MobileApplicationsMetricsJSONByMobileApplicationIDGet structure.
type V2MobileApplicationsMetricsJSONByMobileApplicationIDGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetOK creates a V2MobileApplicationsMetricsJSONByMobileApplicationIDGetOK with default headers values
func NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetOK() *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetOK {
	return &V2MobileApplicationsMetricsJSONByMobileApplicationIDGetOK{}
}

/*V2MobileApplicationsMetricsJSONByMobileApplicationIDGetOK handles this case with default header values.

OK
*/
type V2MobileApplicationsMetricsJSONByMobileApplicationIDGetOK struct {
	Payload *models.MetricParserResponse
}

func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetOK) Error() string {
	return fmt.Sprintf("[GET /v2/mobile_applications/{mobile_application_id}/metrics.json][%d] v2MobileApplicationsMetricsJsonByMobileApplicationIdGetOK  %+v", 200, o.Payload)
}

func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MetricParserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetUnauthorized creates a V2MobileApplicationsMetricsJSONByMobileApplicationIDGetUnauthorized with default headers values
func NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetUnauthorized() *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetUnauthorized {
	return &V2MobileApplicationsMetricsJSONByMobileApplicationIDGetUnauthorized{}
}

/*V2MobileApplicationsMetricsJSONByMobileApplicationIDGetUnauthorized handles this case with default header values.

Invalid API key
*/
type V2MobileApplicationsMetricsJSONByMobileApplicationIDGetUnauthorized struct {
	Payload interface{}
}

func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v2/mobile_applications/{mobile_application_id}/metrics.json][%d] v2MobileApplicationsMetricsJsonByMobileApplicationIdGetUnauthorized  %+v", 401, o.Payload)
}

func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetForbidden creates a V2MobileApplicationsMetricsJSONByMobileApplicationIDGetForbidden with default headers values
func NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetForbidden() *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetForbidden {
	return &V2MobileApplicationsMetricsJSONByMobileApplicationIDGetForbidden{}
}

/*V2MobileApplicationsMetricsJSONByMobileApplicationIDGetForbidden handles this case with default header values.

New Relic API access has not been enabled
*/
type V2MobileApplicationsMetricsJSONByMobileApplicationIDGetForbidden struct {
	Payload interface{}
}

func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetForbidden) Error() string {
	return fmt.Sprintf("[GET /v2/mobile_applications/{mobile_application_id}/metrics.json][%d] v2MobileApplicationsMetricsJsonByMobileApplicationIdGetForbidden  %+v", 403, o.Payload)
}

func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetDefault creates a V2MobileApplicationsMetricsJSONByMobileApplicationIDGetDefault with default headers values
func NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetDefault(code int) *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetDefault {
	return &V2MobileApplicationsMetricsJSONByMobileApplicationIDGetDefault{
		_statusCode: code,
	}
}

/*V2MobileApplicationsMetricsJSONByMobileApplicationIDGetDefault handles this case with default header values.

A server error occurred, please contact <a href="http://support.newrelic.com">New Relic support</a>
*/
type V2MobileApplicationsMetricsJSONByMobileApplicationIDGetDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the v2 mobile applications metrics Json by mobile application Id get default response
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetDefault) Code() int {
	return o._statusCode
}

func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetDefault) Error() string {
	return fmt.Sprintf("[GET /v2/mobile_applications/{mobile_application_id}/metrics.json][%d] V2MobileApplicationsMetricsJsonByMobileApplicationIdGet default  %+v", o._statusCode, o.Payload)
}

func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
