// Code generated by go-swagger; DO NOT EDIT.

package mobile_applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams creates a new V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams object
// with the default values initialized.
func NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams() *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams {
	var ()
	return &V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetParamsWithTimeout creates a new V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetParamsWithTimeout(timeout time.Duration) *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams {
	var ()
	return &V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams{

		timeout: timeout,
	}
}

// NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetParamsWithContext creates a new V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetParamsWithContext(ctx context.Context) *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams {
	var ()
	return &V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams{

		Context: ctx,
	}
}

// NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetParamsWithHTTPClient creates a new V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2MobileApplicationsMetricsJSONByMobileApplicationIDGetParamsWithHTTPClient(client *http.Client) *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams {
	var ()
	return &V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams{
		HTTPClient: client,
	}
}

/*V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams contains all the parameters to send to the API endpoint
for the v2 mobile applications metrics Json by mobile application Id get operation typically these are written to a http.Request
*/
type V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams struct {

	/*Cursor
	  Cursor for next page (replacing page param)

	*/
	Cursor *string
	/*MobileApplicationID
	  Mobile application ID

	*/
	MobileApplicationID int64
	/*Name
	  Filter metrics by name

	*/
	Name *string
	/*Page
	  Pagination index (will be deprecated)

	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) WithTimeout(timeout time.Duration) *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) WithContext(ctx context.Context) *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) WithHTTPClient(client *http.Client) *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCursor adds the cursor to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) WithCursor(cursor *string) *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams {
	o.SetCursor(cursor)
	return o
}

// SetCursor adds the cursor to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) SetCursor(cursor *string) {
	o.Cursor = cursor
}

// WithMobileApplicationID adds the mobileApplicationID to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) WithMobileApplicationID(mobileApplicationID int64) *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams {
	o.SetMobileApplicationID(mobileApplicationID)
	return o
}

// SetMobileApplicationID adds the mobileApplicationId to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) SetMobileApplicationID(mobileApplicationID int64) {
	o.MobileApplicationID = mobileApplicationID
}

// WithName adds the name to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) WithName(name *string) *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) SetName(name *string) {
	o.Name = name
}

// WithPage adds the page to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) WithPage(page *int64) *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the v2 mobile applications metrics Json by mobile application Id get params
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *V2MobileApplicationsMetricsJSONByMobileApplicationIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cursor != nil {

		// query param cursor
		var qrCursor string
		if o.Cursor != nil {
			qrCursor = *o.Cursor
		}
		qCursor := qrCursor
		if qCursor != "" {
			if err := r.SetQueryParam("cursor", qCursor); err != nil {
				return err
			}
		}

	}

	// path param mobile_application_id
	if err := r.SetPathParam("mobile_application_id", swag.FormatInt64(o.MobileApplicationID)); err != nil {
		return err
	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
