// Code generated by go-swagger; DO NOT EDIT.

package servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewV2ServersJSONByIDDeleteParams creates a new V2ServersJSONByIDDeleteParams object
// with the default values initialized.
func NewV2ServersJSONByIDDeleteParams() *V2ServersJSONByIDDeleteParams {
	var ()
	return &V2ServersJSONByIDDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2ServersJSONByIDDeleteParamsWithTimeout creates a new V2ServersJSONByIDDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2ServersJSONByIDDeleteParamsWithTimeout(timeout time.Duration) *V2ServersJSONByIDDeleteParams {
	var ()
	return &V2ServersJSONByIDDeleteParams{

		timeout: timeout,
	}
}

// NewV2ServersJSONByIDDeleteParamsWithContext creates a new V2ServersJSONByIDDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2ServersJSONByIDDeleteParamsWithContext(ctx context.Context) *V2ServersJSONByIDDeleteParams {
	var ()
	return &V2ServersJSONByIDDeleteParams{

		Context: ctx,
	}
}

// NewV2ServersJSONByIDDeleteParamsWithHTTPClient creates a new V2ServersJSONByIDDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2ServersJSONByIDDeleteParamsWithHTTPClient(client *http.Client) *V2ServersJSONByIDDeleteParams {
	var ()
	return &V2ServersJSONByIDDeleteParams{
		HTTPClient: client,
	}
}

/*V2ServersJSONByIDDeleteParams contains all the parameters to send to the API endpoint
for the v2 servers Json by Id delete operation typically these are written to a http.Request
*/
type V2ServersJSONByIDDeleteParams struct {

	/*ServerID
	  Server ID

	*/
	ServerID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 servers Json by Id delete params
func (o *V2ServersJSONByIDDeleteParams) WithTimeout(timeout time.Duration) *V2ServersJSONByIDDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 servers Json by Id delete params
func (o *V2ServersJSONByIDDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 servers Json by Id delete params
func (o *V2ServersJSONByIDDeleteParams) WithContext(ctx context.Context) *V2ServersJSONByIDDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 servers Json by Id delete params
func (o *V2ServersJSONByIDDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 servers Json by Id delete params
func (o *V2ServersJSONByIDDeleteParams) WithHTTPClient(client *http.Client) *V2ServersJSONByIDDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 servers Json by Id delete params
func (o *V2ServersJSONByIDDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the v2 servers Json by Id delete params
func (o *V2ServersJSONByIDDeleteParams) WithServerID(serverID int64) *V2ServersJSONByIDDeleteParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the v2 servers Json by Id delete params
func (o *V2ServersJSONByIDDeleteParams) SetServerID(serverID int64) {
	o.ServerID = serverID
}

// WriteToRequest writes these params to a swagger request
func (o *V2ServersJSONByIDDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param server_id
	if err := r.SetPathParam("server_id", swag.FormatInt64(o.ServerID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
