// Code generated by go-swagger; DO NOT EDIT.

package servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewV2ServersJSONByIDGetParams creates a new V2ServersJSONByIDGetParams object
// with the default values initialized.
func NewV2ServersJSONByIDGetParams() *V2ServersJSONByIDGetParams {
	var ()
	return &V2ServersJSONByIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2ServersJSONByIDGetParamsWithTimeout creates a new V2ServersJSONByIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2ServersJSONByIDGetParamsWithTimeout(timeout time.Duration) *V2ServersJSONByIDGetParams {
	var ()
	return &V2ServersJSONByIDGetParams{

		timeout: timeout,
	}
}

// NewV2ServersJSONByIDGetParamsWithContext creates a new V2ServersJSONByIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2ServersJSONByIDGetParamsWithContext(ctx context.Context) *V2ServersJSONByIDGetParams {
	var ()
	return &V2ServersJSONByIDGetParams{

		Context: ctx,
	}
}

// NewV2ServersJSONByIDGetParamsWithHTTPClient creates a new V2ServersJSONByIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2ServersJSONByIDGetParamsWithHTTPClient(client *http.Client) *V2ServersJSONByIDGetParams {
	var ()
	return &V2ServersJSONByIDGetParams{
		HTTPClient: client,
	}
}

/*V2ServersJSONByIDGetParams contains all the parameters to send to the API endpoint
for the v2 servers Json by Id get operation typically these are written to a http.Request
*/
type V2ServersJSONByIDGetParams struct {

	/*ServerID
	  Server ID

	*/
	ServerID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 servers Json by Id get params
func (o *V2ServersJSONByIDGetParams) WithTimeout(timeout time.Duration) *V2ServersJSONByIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 servers Json by Id get params
func (o *V2ServersJSONByIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 servers Json by Id get params
func (o *V2ServersJSONByIDGetParams) WithContext(ctx context.Context) *V2ServersJSONByIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 servers Json by Id get params
func (o *V2ServersJSONByIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 servers Json by Id get params
func (o *V2ServersJSONByIDGetParams) WithHTTPClient(client *http.Client) *V2ServersJSONByIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 servers Json by Id get params
func (o *V2ServersJSONByIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the v2 servers Json by Id get params
func (o *V2ServersJSONByIDGetParams) WithServerID(serverID int64) *V2ServersJSONByIDGetParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the v2 servers Json by Id get params
func (o *V2ServersJSONByIDGetParams) SetServerID(serverID int64) {
	o.ServerID = serverID
}

// WriteToRequest writes these params to a swagger request
func (o *V2ServersJSONByIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param server_id
	if err := r.SetPathParam("server_id", swag.FormatInt64(o.ServerID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
