// Code generated by go-swagger; DO NOT EDIT.

package alerts_external_service_conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// V2AlertsExternalServiceConditionsJSONByIDPutReader is a Reader for the V2AlertsExternalServiceConditionsJSONByIDPut structure.
type V2AlertsExternalServiceConditionsJSONByIDPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2AlertsExternalServiceConditionsJSONByIDPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewV2AlertsExternalServiceConditionsJSONByIDPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewV2AlertsExternalServiceConditionsJSONByIDPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewV2AlertsExternalServiceConditionsJSONByIDPutForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewV2AlertsExternalServiceConditionsJSONByIDPutNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewV2AlertsExternalServiceConditionsJSONByIDPutUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewV2AlertsExternalServiceConditionsJSONByIDPutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2AlertsExternalServiceConditionsJSONByIDPutOK creates a V2AlertsExternalServiceConditionsJSONByIDPutOK with default headers values
func NewV2AlertsExternalServiceConditionsJSONByIDPutOK() *V2AlertsExternalServiceConditionsJSONByIDPutOK {
	return &V2AlertsExternalServiceConditionsJSONByIDPutOK{}
}

/*V2AlertsExternalServiceConditionsJSONByIDPutOK handles this case with default header values.

OK
*/
type V2AlertsExternalServiceConditionsJSONByIDPutOK struct {
	Payload *models.ExternalServiceConditionResponse
}

func (o *V2AlertsExternalServiceConditionsJSONByIDPutOK) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_external_service_conditions/{condition_id}.json][%d] v2AlertsExternalServiceConditionsJsonByIdPutOK  %+v", 200, o.Payload)
}

func (o *V2AlertsExternalServiceConditionsJSONByIDPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExternalServiceConditionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsExternalServiceConditionsJSONByIDPutUnauthorized creates a V2AlertsExternalServiceConditionsJSONByIDPutUnauthorized with default headers values
func NewV2AlertsExternalServiceConditionsJSONByIDPutUnauthorized() *V2AlertsExternalServiceConditionsJSONByIDPutUnauthorized {
	return &V2AlertsExternalServiceConditionsJSONByIDPutUnauthorized{}
}

/*V2AlertsExternalServiceConditionsJSONByIDPutUnauthorized handles this case with default header values.

Invalid API key
*/
type V2AlertsExternalServiceConditionsJSONByIDPutUnauthorized struct {
	Payload interface{}
}

func (o *V2AlertsExternalServiceConditionsJSONByIDPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_external_service_conditions/{condition_id}.json][%d] v2AlertsExternalServiceConditionsJsonByIdPutUnauthorized  %+v", 401, o.Payload)
}

func (o *V2AlertsExternalServiceConditionsJSONByIDPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsExternalServiceConditionsJSONByIDPutForbidden creates a V2AlertsExternalServiceConditionsJSONByIDPutForbidden with default headers values
func NewV2AlertsExternalServiceConditionsJSONByIDPutForbidden() *V2AlertsExternalServiceConditionsJSONByIDPutForbidden {
	return &V2AlertsExternalServiceConditionsJSONByIDPutForbidden{}
}

/*V2AlertsExternalServiceConditionsJSONByIDPutForbidden handles this case with default header values.

New Relic API access has not been enabled
*/
type V2AlertsExternalServiceConditionsJSONByIDPutForbidden struct {
	Payload interface{}
}

func (o *V2AlertsExternalServiceConditionsJSONByIDPutForbidden) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_external_service_conditions/{condition_id}.json][%d] v2AlertsExternalServiceConditionsJsonByIdPutForbidden  %+v", 403, o.Payload)
}

func (o *V2AlertsExternalServiceConditionsJSONByIDPutForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsExternalServiceConditionsJSONByIDPutNotFound creates a V2AlertsExternalServiceConditionsJSONByIDPutNotFound with default headers values
func NewV2AlertsExternalServiceConditionsJSONByIDPutNotFound() *V2AlertsExternalServiceConditionsJSONByIDPutNotFound {
	return &V2AlertsExternalServiceConditionsJSONByIDPutNotFound{}
}

/*V2AlertsExternalServiceConditionsJSONByIDPutNotFound handles this case with default header values.

No Alerts condition was found with the given ID
*/
type V2AlertsExternalServiceConditionsJSONByIDPutNotFound struct {
	Payload interface{}
}

func (o *V2AlertsExternalServiceConditionsJSONByIDPutNotFound) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_external_service_conditions/{condition_id}.json][%d] v2AlertsExternalServiceConditionsJsonByIdPutNotFound  %+v", 404, o.Payload)
}

func (o *V2AlertsExternalServiceConditionsJSONByIDPutNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsExternalServiceConditionsJSONByIDPutUnprocessableEntity creates a V2AlertsExternalServiceConditionsJSONByIDPutUnprocessableEntity with default headers values
func NewV2AlertsExternalServiceConditionsJSONByIDPutUnprocessableEntity() *V2AlertsExternalServiceConditionsJSONByIDPutUnprocessableEntity {
	return &V2AlertsExternalServiceConditionsJSONByIDPutUnprocessableEntity{}
}

/*V2AlertsExternalServiceConditionsJSONByIDPutUnprocessableEntity handles this case with default header values.

Validation error occurred while trying to update the alert condition
*/
type V2AlertsExternalServiceConditionsJSONByIDPutUnprocessableEntity struct {
	Payload interface{}
}

func (o *V2AlertsExternalServiceConditionsJSONByIDPutUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_external_service_conditions/{condition_id}.json][%d] v2AlertsExternalServiceConditionsJsonByIdPutUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *V2AlertsExternalServiceConditionsJSONByIDPutUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsExternalServiceConditionsJSONByIDPutDefault creates a V2AlertsExternalServiceConditionsJSONByIDPutDefault with default headers values
func NewV2AlertsExternalServiceConditionsJSONByIDPutDefault(code int) *V2AlertsExternalServiceConditionsJSONByIDPutDefault {
	return &V2AlertsExternalServiceConditionsJSONByIDPutDefault{
		_statusCode: code,
	}
}

/*V2AlertsExternalServiceConditionsJSONByIDPutDefault handles this case with default header values.

A server error occurred, please contact <a href="http://support.newrelic.com">New Relic support</a>
*/
type V2AlertsExternalServiceConditionsJSONByIDPutDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the v2 alerts external service conditions Json by Id put default response
func (o *V2AlertsExternalServiceConditionsJSONByIDPutDefault) Code() int {
	return o._statusCode
}

func (o *V2AlertsExternalServiceConditionsJSONByIDPutDefault) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_external_service_conditions/{condition_id}.json][%d] V2AlertsExternalServiceConditionsJsonByIdPut default  %+v", o._statusCode, o.Payload)
}

func (o *V2AlertsExternalServiceConditionsJSONByIDPutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
