// Code generated by go-swagger; DO NOT EDIT.

package alerts_plugins_conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewV2AlertsPluginsConditionsJSONByConditionIDDeleteParams creates a new V2AlertsPluginsConditionsJSONByConditionIDDeleteParams object
// with the default values initialized.
func NewV2AlertsPluginsConditionsJSONByConditionIDDeleteParams() *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams {
	var ()
	return &V2AlertsPluginsConditionsJSONByConditionIDDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2AlertsPluginsConditionsJSONByConditionIDDeleteParamsWithTimeout creates a new V2AlertsPluginsConditionsJSONByConditionIDDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2AlertsPluginsConditionsJSONByConditionIDDeleteParamsWithTimeout(timeout time.Duration) *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams {
	var ()
	return &V2AlertsPluginsConditionsJSONByConditionIDDeleteParams{

		timeout: timeout,
	}
}

// NewV2AlertsPluginsConditionsJSONByConditionIDDeleteParamsWithContext creates a new V2AlertsPluginsConditionsJSONByConditionIDDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2AlertsPluginsConditionsJSONByConditionIDDeleteParamsWithContext(ctx context.Context) *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams {
	var ()
	return &V2AlertsPluginsConditionsJSONByConditionIDDeleteParams{

		Context: ctx,
	}
}

// NewV2AlertsPluginsConditionsJSONByConditionIDDeleteParamsWithHTTPClient creates a new V2AlertsPluginsConditionsJSONByConditionIDDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2AlertsPluginsConditionsJSONByConditionIDDeleteParamsWithHTTPClient(client *http.Client) *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams {
	var ()
	return &V2AlertsPluginsConditionsJSONByConditionIDDeleteParams{
		HTTPClient: client,
	}
}

/*V2AlertsPluginsConditionsJSONByConditionIDDeleteParams contains all the parameters to send to the API endpoint
for the v2 alerts plugins conditions Json by condition Id delete operation typically these are written to a http.Request
*/
type V2AlertsPluginsConditionsJSONByConditionIDDeleteParams struct {

	/*ConditionID
	  Alerts condition ID

	*/
	ConditionID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 alerts plugins conditions Json by condition Id delete params
func (o *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams) WithTimeout(timeout time.Duration) *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 alerts plugins conditions Json by condition Id delete params
func (o *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 alerts plugins conditions Json by condition Id delete params
func (o *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams) WithContext(ctx context.Context) *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 alerts plugins conditions Json by condition Id delete params
func (o *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 alerts plugins conditions Json by condition Id delete params
func (o *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams) WithHTTPClient(client *http.Client) *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 alerts plugins conditions Json by condition Id delete params
func (o *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConditionID adds the conditionID to the v2 alerts plugins conditions Json by condition Id delete params
func (o *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams) WithConditionID(conditionID int64) *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams {
	o.SetConditionID(conditionID)
	return o
}

// SetConditionID adds the conditionId to the v2 alerts plugins conditions Json by condition Id delete params
func (o *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams) SetConditionID(conditionID int64) {
	o.ConditionID = conditionID
}

// WriteToRequest writes these params to a swagger request
func (o *V2AlertsPluginsConditionsJSONByConditionIDDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param condition_id
	if err := r.SetPathParam("condition_id", swag.FormatInt64(o.ConditionID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
