// Code generated by go-swagger; DO NOT EDIT.

package alerts_plugins_conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// V2AlertsPluginsConditionsJSONByIDPutReader is a Reader for the V2AlertsPluginsConditionsJSONByIDPut structure.
type V2AlertsPluginsConditionsJSONByIDPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2AlertsPluginsConditionsJSONByIDPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewV2AlertsPluginsConditionsJSONByIDPutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewV2AlertsPluginsConditionsJSONByIDPutUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewV2AlertsPluginsConditionsJSONByIDPutForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewV2AlertsPluginsConditionsJSONByIDPutNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewV2AlertsPluginsConditionsJSONByIDPutUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewV2AlertsPluginsConditionsJSONByIDPutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2AlertsPluginsConditionsJSONByIDPutOK creates a V2AlertsPluginsConditionsJSONByIDPutOK with default headers values
func NewV2AlertsPluginsConditionsJSONByIDPutOK() *V2AlertsPluginsConditionsJSONByIDPutOK {
	return &V2AlertsPluginsConditionsJSONByIDPutOK{}
}

/*V2AlertsPluginsConditionsJSONByIDPutOK handles this case with default header values.

OK
*/
type V2AlertsPluginsConditionsJSONByIDPutOK struct {
	Payload *models.PluginsConditionResponse
}

func (o *V2AlertsPluginsConditionsJSONByIDPutOK) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_plugins_conditions/{condition_id}.json][%d] v2AlertsPluginsConditionsJsonByIdPutOK  %+v", 200, o.Payload)
}

func (o *V2AlertsPluginsConditionsJSONByIDPutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PluginsConditionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsPluginsConditionsJSONByIDPutUnauthorized creates a V2AlertsPluginsConditionsJSONByIDPutUnauthorized with default headers values
func NewV2AlertsPluginsConditionsJSONByIDPutUnauthorized() *V2AlertsPluginsConditionsJSONByIDPutUnauthorized {
	return &V2AlertsPluginsConditionsJSONByIDPutUnauthorized{}
}

/*V2AlertsPluginsConditionsJSONByIDPutUnauthorized handles this case with default header values.

Invalid API key
*/
type V2AlertsPluginsConditionsJSONByIDPutUnauthorized struct {
	Payload interface{}
}

func (o *V2AlertsPluginsConditionsJSONByIDPutUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_plugins_conditions/{condition_id}.json][%d] v2AlertsPluginsConditionsJsonByIdPutUnauthorized  %+v", 401, o.Payload)
}

func (o *V2AlertsPluginsConditionsJSONByIDPutUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsPluginsConditionsJSONByIDPutForbidden creates a V2AlertsPluginsConditionsJSONByIDPutForbidden with default headers values
func NewV2AlertsPluginsConditionsJSONByIDPutForbidden() *V2AlertsPluginsConditionsJSONByIDPutForbidden {
	return &V2AlertsPluginsConditionsJSONByIDPutForbidden{}
}

/*V2AlertsPluginsConditionsJSONByIDPutForbidden handles this case with default header values.

New Relic API access has not been enabled
*/
type V2AlertsPluginsConditionsJSONByIDPutForbidden struct {
	Payload interface{}
}

func (o *V2AlertsPluginsConditionsJSONByIDPutForbidden) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_plugins_conditions/{condition_id}.json][%d] v2AlertsPluginsConditionsJsonByIdPutForbidden  %+v", 403, o.Payload)
}

func (o *V2AlertsPluginsConditionsJSONByIDPutForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsPluginsConditionsJSONByIDPutNotFound creates a V2AlertsPluginsConditionsJSONByIDPutNotFound with default headers values
func NewV2AlertsPluginsConditionsJSONByIDPutNotFound() *V2AlertsPluginsConditionsJSONByIDPutNotFound {
	return &V2AlertsPluginsConditionsJSONByIDPutNotFound{}
}

/*V2AlertsPluginsConditionsJSONByIDPutNotFound handles this case with default header values.

No Alerts condition was found with the given ID
*/
type V2AlertsPluginsConditionsJSONByIDPutNotFound struct {
	Payload interface{}
}

func (o *V2AlertsPluginsConditionsJSONByIDPutNotFound) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_plugins_conditions/{condition_id}.json][%d] v2AlertsPluginsConditionsJsonByIdPutNotFound  %+v", 404, o.Payload)
}

func (o *V2AlertsPluginsConditionsJSONByIDPutNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsPluginsConditionsJSONByIDPutUnprocessableEntity creates a V2AlertsPluginsConditionsJSONByIDPutUnprocessableEntity with default headers values
func NewV2AlertsPluginsConditionsJSONByIDPutUnprocessableEntity() *V2AlertsPluginsConditionsJSONByIDPutUnprocessableEntity {
	return &V2AlertsPluginsConditionsJSONByIDPutUnprocessableEntity{}
}

/*V2AlertsPluginsConditionsJSONByIDPutUnprocessableEntity handles this case with default header values.

Validation error occurred while trying to update the alert condition
*/
type V2AlertsPluginsConditionsJSONByIDPutUnprocessableEntity struct {
	Payload interface{}
}

func (o *V2AlertsPluginsConditionsJSONByIDPutUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_plugins_conditions/{condition_id}.json][%d] v2AlertsPluginsConditionsJsonByIdPutUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *V2AlertsPluginsConditionsJSONByIDPutUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2AlertsPluginsConditionsJSONByIDPutDefault creates a V2AlertsPluginsConditionsJSONByIDPutDefault with default headers values
func NewV2AlertsPluginsConditionsJSONByIDPutDefault(code int) *V2AlertsPluginsConditionsJSONByIDPutDefault {
	return &V2AlertsPluginsConditionsJSONByIDPutDefault{
		_statusCode: code,
	}
}

/*V2AlertsPluginsConditionsJSONByIDPutDefault handles this case with default header values.

A server error occurred, please contact <a href="http://support.newrelic.com">New Relic support</a>
*/
type V2AlertsPluginsConditionsJSONByIDPutDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the v2 alerts plugins conditions Json by Id put default response
func (o *V2AlertsPluginsConditionsJSONByIDPutDefault) Code() int {
	return o._statusCode
}

func (o *V2AlertsPluginsConditionsJSONByIDPutDefault) Error() string {
	return fmt.Sprintf("[PUT /v2/alerts_plugins_conditions/{condition_id}.json][%d] V2AlertsPluginsConditionsJsonByIdPut default  %+v", o._statusCode, o.Payload)
}

func (o *V2AlertsPluginsConditionsJSONByIDPutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
