// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// V2UsersJSONGetReader is a Reader for the V2UsersJSONGet structure.
type V2UsersJSONGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2UsersJSONGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewV2UsersJSONGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewV2UsersJSONGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewV2UsersJSONGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewV2UsersJSONGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2UsersJSONGetOK creates a V2UsersJSONGetOK with default headers values
func NewV2UsersJSONGetOK() *V2UsersJSONGetOK {
	return &V2UsersJSONGetOK{}
}

/*V2UsersJSONGetOK handles this case with default header values.

OK
*/
type V2UsersJSONGetOK struct {
	Payload *models.UserResponse
}

func (o *V2UsersJSONGetOK) Error() string {
	return fmt.Sprintf("[GET /v2/users.json][%d] v2UsersJsonGetOK  %+v", 200, o.Payload)
}

func (o *V2UsersJSONGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UsersJSONGetUnauthorized creates a V2UsersJSONGetUnauthorized with default headers values
func NewV2UsersJSONGetUnauthorized() *V2UsersJSONGetUnauthorized {
	return &V2UsersJSONGetUnauthorized{}
}

/*V2UsersJSONGetUnauthorized handles this case with default header values.

Invalid API key
*/
type V2UsersJSONGetUnauthorized struct {
	Payload interface{}
}

func (o *V2UsersJSONGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v2/users.json][%d] v2UsersJsonGetUnauthorized  %+v", 401, o.Payload)
}

func (o *V2UsersJSONGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UsersJSONGetForbidden creates a V2UsersJSONGetForbidden with default headers values
func NewV2UsersJSONGetForbidden() *V2UsersJSONGetForbidden {
	return &V2UsersJSONGetForbidden{}
}

/*V2UsersJSONGetForbidden handles this case with default header values.

New Relic API access has not been enabled
*/
type V2UsersJSONGetForbidden struct {
	Payload interface{}
}

func (o *V2UsersJSONGetForbidden) Error() string {
	return fmt.Sprintf("[GET /v2/users.json][%d] v2UsersJsonGetForbidden  %+v", 403, o.Payload)
}

func (o *V2UsersJSONGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UsersJSONGetDefault creates a V2UsersJSONGetDefault with default headers values
func NewV2UsersJSONGetDefault(code int) *V2UsersJSONGetDefault {
	return &V2UsersJSONGetDefault{
		_statusCode: code,
	}
}

/*V2UsersJSONGetDefault handles this case with default header values.

A server error occurred, please contact <a href="http://support.newrelic.com">New Relic support</a>
*/
type V2UsersJSONGetDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the v2 users Json get default response
func (o *V2UsersJSONGetDefault) Code() int {
	return o._statusCode
}

func (o *V2UsersJSONGetDefault) Error() string {
	return fmt.Sprintf("[GET /v2/users.json][%d] V2UsersJsonGet default  %+v", o._statusCode, o.Payload)
}

func (o *V2UsersJSONGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
