// Code generated by go-swagger; DO NOT EDIT.

package application_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewV2ApplicationsInstancesJSONByApplicationIDAndIDGetParams creates a new V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams object
// with the default values initialized.
func NewV2ApplicationsInstancesJSONByApplicationIDAndIDGetParams() *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams {
	var ()
	return &V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2ApplicationsInstancesJSONByApplicationIDAndIDGetParamsWithTimeout creates a new V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2ApplicationsInstancesJSONByApplicationIDAndIDGetParamsWithTimeout(timeout time.Duration) *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams {
	var ()
	return &V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams{

		timeout: timeout,
	}
}

// NewV2ApplicationsInstancesJSONByApplicationIDAndIDGetParamsWithContext creates a new V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2ApplicationsInstancesJSONByApplicationIDAndIDGetParamsWithContext(ctx context.Context) *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams {
	var ()
	return &V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams{

		Context: ctx,
	}
}

// NewV2ApplicationsInstancesJSONByApplicationIDAndIDGetParamsWithHTTPClient creates a new V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2ApplicationsInstancesJSONByApplicationIDAndIDGetParamsWithHTTPClient(client *http.Client) *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams {
	var ()
	return &V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams{
		HTTPClient: client,
	}
}

/*V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams contains all the parameters to send to the API endpoint
for the v2 applications instances Json by application Id and Id get operation typically these are written to a http.Request
*/
type V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams struct {

	/*ApplicationID
	  Application ID

	*/
	ApplicationID int64
	/*InstanceID
	  Application instance ID

	*/
	InstanceID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 applications instances Json by application Id and Id get params
func (o *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams) WithTimeout(timeout time.Duration) *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 applications instances Json by application Id and Id get params
func (o *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 applications instances Json by application Id and Id get params
func (o *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams) WithContext(ctx context.Context) *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 applications instances Json by application Id and Id get params
func (o *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 applications instances Json by application Id and Id get params
func (o *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams) WithHTTPClient(client *http.Client) *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 applications instances Json by application Id and Id get params
func (o *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplicationID adds the applicationID to the v2 applications instances Json by application Id and Id get params
func (o *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams) WithApplicationID(applicationID int64) *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams {
	o.SetApplicationID(applicationID)
	return o
}

// SetApplicationID adds the applicationId to the v2 applications instances Json by application Id and Id get params
func (o *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams) SetApplicationID(applicationID int64) {
	o.ApplicationID = applicationID
}

// WithInstanceID adds the instanceID to the v2 applications instances Json by application Id and Id get params
func (o *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams) WithInstanceID(instanceID int64) *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the v2 applications instances Json by application Id and Id get params
func (o *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams) SetInstanceID(instanceID int64) {
	o.InstanceID = instanceID
}

// WriteToRequest writes these params to a swagger request
func (o *V2ApplicationsInstancesJSONByApplicationIDAndIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param application_id
	if err := r.SetPathParam("application_id", swag.FormatInt64(o.ApplicationID)); err != nil {
		return err
	}

	// path param instance_id
	if err := r.SetPathParam("instance_id", swag.FormatInt64(o.InstanceID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
