// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewV2ComponentsMetricsJSONByComponentIDGetParams creates a new V2ComponentsMetricsJSONByComponentIDGetParams object
// with the default values initialized.
func NewV2ComponentsMetricsJSONByComponentIDGetParams() *V2ComponentsMetricsJSONByComponentIDGetParams {
	var ()
	return &V2ComponentsMetricsJSONByComponentIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2ComponentsMetricsJSONByComponentIDGetParamsWithTimeout creates a new V2ComponentsMetricsJSONByComponentIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2ComponentsMetricsJSONByComponentIDGetParamsWithTimeout(timeout time.Duration) *V2ComponentsMetricsJSONByComponentIDGetParams {
	var ()
	return &V2ComponentsMetricsJSONByComponentIDGetParams{

		timeout: timeout,
	}
}

// NewV2ComponentsMetricsJSONByComponentIDGetParamsWithContext creates a new V2ComponentsMetricsJSONByComponentIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2ComponentsMetricsJSONByComponentIDGetParamsWithContext(ctx context.Context) *V2ComponentsMetricsJSONByComponentIDGetParams {
	var ()
	return &V2ComponentsMetricsJSONByComponentIDGetParams{

		Context: ctx,
	}
}

// NewV2ComponentsMetricsJSONByComponentIDGetParamsWithHTTPClient creates a new V2ComponentsMetricsJSONByComponentIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2ComponentsMetricsJSONByComponentIDGetParamsWithHTTPClient(client *http.Client) *V2ComponentsMetricsJSONByComponentIDGetParams {
	var ()
	return &V2ComponentsMetricsJSONByComponentIDGetParams{
		HTTPClient: client,
	}
}

/*V2ComponentsMetricsJSONByComponentIDGetParams contains all the parameters to send to the API endpoint
for the v2 components metrics Json by component Id get operation typically these are written to a http.Request
*/
type V2ComponentsMetricsJSONByComponentIDGetParams struct {

	/*ComponentID
	  Component ID

	*/
	ComponentID int64
	/*Cursor
	  Cursor for next page (replacing page param)

	*/
	Cursor *string
	/*Name
	  Filter metrics by name

	*/
	Name *string
	/*Page
	  Pagination index (will be deprecated)

	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) WithTimeout(timeout time.Duration) *V2ComponentsMetricsJSONByComponentIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) WithContext(ctx context.Context) *V2ComponentsMetricsJSONByComponentIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) WithHTTPClient(client *http.Client) *V2ComponentsMetricsJSONByComponentIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithComponentID adds the componentID to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) WithComponentID(componentID int64) *V2ComponentsMetricsJSONByComponentIDGetParams {
	o.SetComponentID(componentID)
	return o
}

// SetComponentID adds the componentId to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) SetComponentID(componentID int64) {
	o.ComponentID = componentID
}

// WithCursor adds the cursor to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) WithCursor(cursor *string) *V2ComponentsMetricsJSONByComponentIDGetParams {
	o.SetCursor(cursor)
	return o
}

// SetCursor adds the cursor to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) SetCursor(cursor *string) {
	o.Cursor = cursor
}

// WithName adds the name to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) WithName(name *string) *V2ComponentsMetricsJSONByComponentIDGetParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) SetName(name *string) {
	o.Name = name
}

// WithPage adds the page to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) WithPage(page *int64) *V2ComponentsMetricsJSONByComponentIDGetParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the v2 components metrics Json by component Id get params
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *V2ComponentsMetricsJSONByComponentIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param component_id
	if err := r.SetPathParam("component_id", swag.FormatInt64(o.ComponentID)); err != nil {
		return err
	}

	if o.Cursor != nil {

		// query param cursor
		var qrCursor string
		if o.Cursor != nil {
			qrCursor = *o.Cursor
		}
		qCursor := qrCursor
		if qCursor != "" {
			if err := r.SetQueryParam("cursor", qCursor); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
