// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// V2ComponentsJSONGetReader is a Reader for the V2ComponentsJSONGet structure.
type V2ComponentsJSONGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2ComponentsJSONGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewV2ComponentsJSONGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewV2ComponentsJSONGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewV2ComponentsJSONGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewV2ComponentsJSONGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2ComponentsJSONGetOK creates a V2ComponentsJSONGetOK with default headers values
func NewV2ComponentsJSONGetOK() *V2ComponentsJSONGetOK {
	return &V2ComponentsJSONGetOK{}
}

/*V2ComponentsJSONGetOK handles this case with default header values.

OK
*/
type V2ComponentsJSONGetOK struct {
	Payload *models.ComponentResponse
}

func (o *V2ComponentsJSONGetOK) Error() string {
	return fmt.Sprintf("[GET /v2/components.json][%d] v2ComponentsJsonGetOK  %+v", 200, o.Payload)
}

func (o *V2ComponentsJSONGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ComponentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2ComponentsJSONGetUnauthorized creates a V2ComponentsJSONGetUnauthorized with default headers values
func NewV2ComponentsJSONGetUnauthorized() *V2ComponentsJSONGetUnauthorized {
	return &V2ComponentsJSONGetUnauthorized{}
}

/*V2ComponentsJSONGetUnauthorized handles this case with default header values.

Invalid API key
*/
type V2ComponentsJSONGetUnauthorized struct {
	Payload interface{}
}

func (o *V2ComponentsJSONGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v2/components.json][%d] v2ComponentsJsonGetUnauthorized  %+v", 401, o.Payload)
}

func (o *V2ComponentsJSONGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2ComponentsJSONGetForbidden creates a V2ComponentsJSONGetForbidden with default headers values
func NewV2ComponentsJSONGetForbidden() *V2ComponentsJSONGetForbidden {
	return &V2ComponentsJSONGetForbidden{}
}

/*V2ComponentsJSONGetForbidden handles this case with default header values.

New Relic API access has not been enabled
*/
type V2ComponentsJSONGetForbidden struct {
	Payload interface{}
}

func (o *V2ComponentsJSONGetForbidden) Error() string {
	return fmt.Sprintf("[GET /v2/components.json][%d] v2ComponentsJsonGetForbidden  %+v", 403, o.Payload)
}

func (o *V2ComponentsJSONGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2ComponentsJSONGetDefault creates a V2ComponentsJSONGetDefault with default headers values
func NewV2ComponentsJSONGetDefault(code int) *V2ComponentsJSONGetDefault {
	return &V2ComponentsJSONGetDefault{
		_statusCode: code,
	}
}

/*V2ComponentsJSONGetDefault handles this case with default header values.

A server error occurred, please contact <a href="http://support.newrelic.com">New Relic support</a>
*/
type V2ComponentsJSONGetDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the v2 components Json get default response
func (o *V2ComponentsJSONGetDefault) Code() int {
	return o._statusCode
}

func (o *V2ComponentsJSONGetDefault) Error() string {
	return fmt.Sprintf("[GET /v2/components.json][%d] V2ComponentsJsonGet default  %+v", o._statusCode, o.Payload)
}

func (o *V2ComponentsJSONGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
