// Code generated by go-swagger; DO NOT EDIT.

package alerts_channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewV2AlertsChannelsJSONGetParams creates a new V2AlertsChannelsJSONGetParams object
// with the default values initialized.
func NewV2AlertsChannelsJSONGetParams() *V2AlertsChannelsJSONGetParams {
	var ()
	return &V2AlertsChannelsJSONGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2AlertsChannelsJSONGetParamsWithTimeout creates a new V2AlertsChannelsJSONGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2AlertsChannelsJSONGetParamsWithTimeout(timeout time.Duration) *V2AlertsChannelsJSONGetParams {
	var ()
	return &V2AlertsChannelsJSONGetParams{

		timeout: timeout,
	}
}

// NewV2AlertsChannelsJSONGetParamsWithContext creates a new V2AlertsChannelsJSONGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2AlertsChannelsJSONGetParamsWithContext(ctx context.Context) *V2AlertsChannelsJSONGetParams {
	var ()
	return &V2AlertsChannelsJSONGetParams{

		Context: ctx,
	}
}

// NewV2AlertsChannelsJSONGetParamsWithHTTPClient creates a new V2AlertsChannelsJSONGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2AlertsChannelsJSONGetParamsWithHTTPClient(client *http.Client) *V2AlertsChannelsJSONGetParams {
	var ()
	return &V2AlertsChannelsJSONGetParams{
		HTTPClient: client,
	}
}

/*V2AlertsChannelsJSONGetParams contains all the parameters to send to the API endpoint
for the v2 alerts channels Json get operation typically these are written to a http.Request
*/
type V2AlertsChannelsJSONGetParams struct {

	/*Page
	  Pagination index

	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 alerts channels Json get params
func (o *V2AlertsChannelsJSONGetParams) WithTimeout(timeout time.Duration) *V2AlertsChannelsJSONGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 alerts channels Json get params
func (o *V2AlertsChannelsJSONGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 alerts channels Json get params
func (o *V2AlertsChannelsJSONGetParams) WithContext(ctx context.Context) *V2AlertsChannelsJSONGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 alerts channels Json get params
func (o *V2AlertsChannelsJSONGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 alerts channels Json get params
func (o *V2AlertsChannelsJSONGetParams) WithHTTPClient(client *http.Client) *V2AlertsChannelsJSONGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 alerts channels Json get params
func (o *V2AlertsChannelsJSONGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the v2 alerts channels Json get params
func (o *V2AlertsChannelsJSONGetParams) WithPage(page *int64) *V2AlertsChannelsJSONGetParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the v2 alerts channels Json get params
func (o *V2AlertsChannelsJSONGetParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *V2AlertsChannelsJSONGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
