// Code generated by go-swagger; DO NOT EDIT.

package alerts_channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewV2AlertsChannelsJSONByChannelIDDeleteParams creates a new V2AlertsChannelsJSONByChannelIDDeleteParams object
// with the default values initialized.
func NewV2AlertsChannelsJSONByChannelIDDeleteParams() *V2AlertsChannelsJSONByChannelIDDeleteParams {
	var ()
	return &V2AlertsChannelsJSONByChannelIDDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2AlertsChannelsJSONByChannelIDDeleteParamsWithTimeout creates a new V2AlertsChannelsJSONByChannelIDDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2AlertsChannelsJSONByChannelIDDeleteParamsWithTimeout(timeout time.Duration) *V2AlertsChannelsJSONByChannelIDDeleteParams {
	var ()
	return &V2AlertsChannelsJSONByChannelIDDeleteParams{

		timeout: timeout,
	}
}

// NewV2AlertsChannelsJSONByChannelIDDeleteParamsWithContext creates a new V2AlertsChannelsJSONByChannelIDDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2AlertsChannelsJSONByChannelIDDeleteParamsWithContext(ctx context.Context) *V2AlertsChannelsJSONByChannelIDDeleteParams {
	var ()
	return &V2AlertsChannelsJSONByChannelIDDeleteParams{

		Context: ctx,
	}
}

// NewV2AlertsChannelsJSONByChannelIDDeleteParamsWithHTTPClient creates a new V2AlertsChannelsJSONByChannelIDDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2AlertsChannelsJSONByChannelIDDeleteParamsWithHTTPClient(client *http.Client) *V2AlertsChannelsJSONByChannelIDDeleteParams {
	var ()
	return &V2AlertsChannelsJSONByChannelIDDeleteParams{
		HTTPClient: client,
	}
}

/*V2AlertsChannelsJSONByChannelIDDeleteParams contains all the parameters to send to the API endpoint
for the v2 alerts channels Json by channel Id delete operation typically these are written to a http.Request
*/
type V2AlertsChannelsJSONByChannelIDDeleteParams struct {

	/*ChannelID
	  Channel ID

	*/
	ChannelID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 alerts channels Json by channel Id delete params
func (o *V2AlertsChannelsJSONByChannelIDDeleteParams) WithTimeout(timeout time.Duration) *V2AlertsChannelsJSONByChannelIDDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 alerts channels Json by channel Id delete params
func (o *V2AlertsChannelsJSONByChannelIDDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 alerts channels Json by channel Id delete params
func (o *V2AlertsChannelsJSONByChannelIDDeleteParams) WithContext(ctx context.Context) *V2AlertsChannelsJSONByChannelIDDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 alerts channels Json by channel Id delete params
func (o *V2AlertsChannelsJSONByChannelIDDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 alerts channels Json by channel Id delete params
func (o *V2AlertsChannelsJSONByChannelIDDeleteParams) WithHTTPClient(client *http.Client) *V2AlertsChannelsJSONByChannelIDDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 alerts channels Json by channel Id delete params
func (o *V2AlertsChannelsJSONByChannelIDDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannelID adds the channelID to the v2 alerts channels Json by channel Id delete params
func (o *V2AlertsChannelsJSONByChannelIDDeleteParams) WithChannelID(channelID int64) *V2AlertsChannelsJSONByChannelIDDeleteParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the v2 alerts channels Json by channel Id delete params
func (o *V2AlertsChannelsJSONByChannelIDDeleteParams) SetChannelID(channelID int64) {
	o.ChannelID = channelID
}

// WriteToRequest writes these params to a swagger request
func (o *V2AlertsChannelsJSONByChannelIDDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param channel_id
	if err := r.SetPathParam("channel_id", swag.FormatInt64(o.ChannelID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
