// Code generated by go-swagger; DO NOT EDIT.

package alerts_incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewV2AlertsIncidentsJSONGetParams creates a new V2AlertsIncidentsJSONGetParams object
// with the default values initialized.
func NewV2AlertsIncidentsJSONGetParams() *V2AlertsIncidentsJSONGetParams {
	var ()
	return &V2AlertsIncidentsJSONGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV2AlertsIncidentsJSONGetParamsWithTimeout creates a new V2AlertsIncidentsJSONGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV2AlertsIncidentsJSONGetParamsWithTimeout(timeout time.Duration) *V2AlertsIncidentsJSONGetParams {
	var ()
	return &V2AlertsIncidentsJSONGetParams{

		timeout: timeout,
	}
}

// NewV2AlertsIncidentsJSONGetParamsWithContext creates a new V2AlertsIncidentsJSONGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV2AlertsIncidentsJSONGetParamsWithContext(ctx context.Context) *V2AlertsIncidentsJSONGetParams {
	var ()
	return &V2AlertsIncidentsJSONGetParams{

		Context: ctx,
	}
}

// NewV2AlertsIncidentsJSONGetParamsWithHTTPClient creates a new V2AlertsIncidentsJSONGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV2AlertsIncidentsJSONGetParamsWithHTTPClient(client *http.Client) *V2AlertsIncidentsJSONGetParams {
	var ()
	return &V2AlertsIncidentsJSONGetParams{
		HTTPClient: client,
	}
}

/*V2AlertsIncidentsJSONGetParams contains all the parameters to send to the API endpoint
for the v2 alerts incidents Json get operation typically these are written to a http.Request
*/
type V2AlertsIncidentsJSONGetParams struct {

	/*OnlyOpen
	  Filter by open incidents

	*/
	OnlyOpen *bool
	/*Page
	  Pagination index

	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v2 alerts incidents Json get params
func (o *V2AlertsIncidentsJSONGetParams) WithTimeout(timeout time.Duration) *V2AlertsIncidentsJSONGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 alerts incidents Json get params
func (o *V2AlertsIncidentsJSONGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 alerts incidents Json get params
func (o *V2AlertsIncidentsJSONGetParams) WithContext(ctx context.Context) *V2AlertsIncidentsJSONGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 alerts incidents Json get params
func (o *V2AlertsIncidentsJSONGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 alerts incidents Json get params
func (o *V2AlertsIncidentsJSONGetParams) WithHTTPClient(client *http.Client) *V2AlertsIncidentsJSONGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 alerts incidents Json get params
func (o *V2AlertsIncidentsJSONGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOnlyOpen adds the onlyOpen to the v2 alerts incidents Json get params
func (o *V2AlertsIncidentsJSONGetParams) WithOnlyOpen(onlyOpen *bool) *V2AlertsIncidentsJSONGetParams {
	o.SetOnlyOpen(onlyOpen)
	return o
}

// SetOnlyOpen adds the onlyOpen to the v2 alerts incidents Json get params
func (o *V2AlertsIncidentsJSONGetParams) SetOnlyOpen(onlyOpen *bool) {
	o.OnlyOpen = onlyOpen
}

// WithPage adds the page to the v2 alerts incidents Json get params
func (o *V2AlertsIncidentsJSONGetParams) WithPage(page *int64) *V2AlertsIncidentsJSONGetParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the v2 alerts incidents Json get params
func (o *V2AlertsIncidentsJSONGetParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *V2AlertsIncidentsJSONGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.OnlyOpen != nil {

		// query param only_open
		var qrOnlyOpen bool
		if o.OnlyOpen != nil {
			qrOnlyOpen = *o.OnlyOpen
		}
		qOnlyOpen := swag.FormatBool(qrOnlyOpen)
		if qOnlyOpen != "" {
			if err := r.SetQueryParam("only_open", qOnlyOpen); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
