// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ApplicationInstanceLinksResponse ApplicationInstanceLinksResponse
// swagger:model ApplicationInstanceLinksResponse
type ApplicationInstanceLinksResponse struct {

	// application
	Application int32 `json:"application,omitempty"`

	// application host
	ApplicationHost int32 `json:"application_host,omitempty"`

	// server
	Server int32 `json:"server,omitempty"`
}

// Validate validates this application instance links response
func (m *ApplicationInstanceLinksResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationInstanceLinksResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationInstanceLinksResponse) UnmarshalBinary(b []byte) error {
	var res ApplicationInstanceLinksResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
