// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ApplicationHostLinksResponse ApplicationHostLinksResponse
// swagger:model ApplicationHostLinksResponse
type ApplicationHostLinksResponse struct {

	// application
	Application int32 `json:"application,omitempty"`

	// application instances
	ApplicationInstances []int32 `json:"application_instances"`

	// server
	Server int32 `json:"server,omitempty"`
}

// Validate validates this application host links response
func (m *ApplicationHostLinksResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationHostLinksResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationHostLinksResponse) UnmarshalBinary(b []byte) error {
	var res ApplicationHostLinksResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
