// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// BrowserApplicationResponse BrowserApplicationResponse
// swagger:model BrowserApplicationResponse
type BrowserApplicationResponse struct {

	// browser application
	BrowserApplication *BrowserApplicationResponseType `json:"browser_application,omitempty"`
}

// Validate validates this browser application response
func (m *BrowserApplicationResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBrowserApplication(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BrowserApplicationResponse) validateBrowserApplication(formats strfmt.Registry) error {

	if swag.IsZero(m.BrowserApplication) { // not required
		return nil
	}

	if m.BrowserApplication != nil {
		if err := m.BrowserApplication.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("browser_application")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BrowserApplicationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BrowserApplicationResponse) UnmarshalBinary(b []byte) error {
	var res BrowserApplicationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
