// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ComponentResponseType ComponentResponseType
// swagger:model ComponentResponseType
type ComponentResponseType struct {

	// health status
	HealthStatus string `json:"health_status,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// summary metrics
	SummaryMetrics []*SummaryMetricResponse `json:"summary_metrics"`
}

// Validate validates this component response type
func (m *ComponentResponseType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSummaryMetrics(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ComponentResponseType) validateSummaryMetrics(formats strfmt.Registry) error {

	if swag.IsZero(m.SummaryMetrics) { // not required
		return nil
	}

	for i := 0; i < len(m.SummaryMetrics); i++ {
		if swag.IsZero(m.SummaryMetrics[i]) { // not required
			continue
		}

		if m.SummaryMetrics[i] != nil {
			if err := m.SummaryMetrics[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("summary_metrics" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ComponentResponseType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComponentResponseType) UnmarshalBinary(b []byte) error {
	var res ComponentResponseType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
