// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// EventLinksResponse EventLinksResponse
// swagger:model EventLinksResponse
type EventLinksResponse struct {

	// downtime
	Downtime int32 `json:"downtime,omitempty"`

	// incidents
	Incidents []int32 `json:"incidents"`
}

// Validate validates this event links response
func (m *EventLinksResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventLinksResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventLinksResponse) UnmarshalBinary(b []byte) error {
	var res EventLinksResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
