// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// IncidentLinksResponse IncidentLinksResponse
// swagger:model IncidentLinksResponse
type IncidentLinksResponse struct {

	// policy id
	PolicyID int32 `json:"policy_id,omitempty"`

	// violations
	Violations []int32 `json:"violations"`
}

// Validate validates this incident links response
func (m *IncidentLinksResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IncidentLinksResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IncidentLinksResponse) UnmarshalBinary(b []byte) error {
	var res IncidentLinksResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
