// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LabelLinksResponse LabelLinksResponse
// swagger:model LabelLinksResponse
type LabelLinksResponse struct {

	// applications
	Applications []int32 `json:"applications"`

	// servers
	Servers []int32 `json:"servers"`
}

// Validate validates this label links response
func (m *LabelLinksResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LabelLinksResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LabelLinksResponse) UnmarshalBinary(b []byte) error {
	var res LabelLinksResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
