// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MobileSummaryDataResponse MobileSummaryDataResponse
// swagger:model MobileSummaryDataResponse
type MobileSummaryDataResponse struct {

	// active users
	ActiveUsers int32 `json:"active_users,omitempty"`

	// calls per session
	CallsPerSession float64 `json:"calls_per_session,omitempty"`

	// failed call rate
	FailedCallRate float64 `json:"failed_call_rate,omitempty"`

	// interaction time
	InteractionTime float64 `json:"interaction_time,omitempty"`

	// launch count
	LaunchCount int32 `json:"launch_count,omitempty"`

	// remote error rate
	RemoteErrorRate float64 `json:"remote_error_rate,omitempty"`

	// response time
	ResponseTime float64 `json:"response_time,omitempty"`

	// throughput
	Throughput float64 `json:"throughput,omitempty"`
}

// Validate validates this mobile summary data response
func (m *MobileSummaryDataResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MobileSummaryDataResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MobileSummaryDataResponse) UnmarshalBinary(b []byte) error {
	var res MobileSummaryDataResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
