// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PluginsConditionResponse PluginsConditionResponse
// swagger:model PluginsConditionResponse
type PluginsConditionResponse struct {

	// plugins condition
	PluginsCondition *PluginsConditionResponseType `json:"plugins_condition,omitempty"`
}

// Validate validates this plugins condition response
func (m *PluginsConditionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePluginsCondition(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PluginsConditionResponse) validatePluginsCondition(formats strfmt.Registry) error {

	if swag.IsZero(m.PluginsCondition) { // not required
		return nil
	}

	if m.PluginsCondition != nil {
		if err := m.PluginsCondition.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("plugins_condition")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PluginsConditionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PluginsConditionResponse) UnmarshalBinary(b []byte) error {
	var res PluginsConditionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
