// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PluginResponseType PluginResponseType
// swagger:model PluginResponseType
type PluginResponseType struct {

	// component agent count
	ComponentAgentCount int32 `json:"component_agent_count,omitempty"`

	// details
	Details *PluginDetailsResponse `json:"details,omitempty"`

	// guid
	GUID string `json:"guid,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// publisher
	Publisher string `json:"publisher,omitempty"`

	// summary metrics
	SummaryMetrics []*SummaryMetricResponse `json:"summary_metrics"`
}

// Validate validates this plugin response type
func (m *PluginResponseType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSummaryMetrics(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PluginResponseType) validateDetails(formats strfmt.Registry) error {

	if swag.IsZero(m.Details) { // not required
		return nil
	}

	if m.Details != nil {
		if err := m.Details.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("details")
			}
			return err
		}
	}

	return nil
}

func (m *PluginResponseType) validateSummaryMetrics(formats strfmt.Registry) error {

	if swag.IsZero(m.SummaryMetrics) { // not required
		return nil
	}

	for i := 0; i < len(m.SummaryMetrics); i++ {
		if swag.IsZero(m.SummaryMetrics[i]) { // not required
			continue
		}

		if m.SummaryMetrics[i] != nil {
			if err := m.SummaryMetrics[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("summary_metrics" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PluginResponseType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PluginResponseType) UnmarshalBinary(b []byte) error {
	var res PluginResponseType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
