// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PolicyChannelsBody PolicyChannelsBody
// swagger:model PolicyChannelsBody
type PolicyChannelsBody struct {

	// channel ids
	ChannelIds []int32 `json:"channel_ids"`

	// id
	ID int32 `json:"id,omitempty"`
}

// Validate validates this policy channels body
func (m *PolicyChannelsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PolicyChannelsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicyChannelsBody) UnmarshalBinary(b []byte) error {
	var res PolicyChannelsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
