// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ServerSummaryResponse ServerSummaryResponse
// swagger:model ServerSummaryResponse
type ServerSummaryResponse struct {

	// cpu
	CPU float64 `json:"cpu,omitempty"`

	// cpu stolen
	CPUStolen float64 `json:"cpu_stolen,omitempty"`

	// disk io
	DiskIo float64 `json:"disk_io,omitempty"`

	// fullest disk
	FullestDisk float64 `json:"fullest_disk,omitempty"`

	// fullest disk free
	FullestDiskFree int32 `json:"fullest_disk_free,omitempty"`

	// memory
	Memory float64 `json:"memory,omitempty"`

	// memory total
	MemoryTotal int32 `json:"memory_total,omitempty"`

	// memory used
	MemoryUsed int32 `json:"memory_used,omitempty"`
}

// Validate validates this server summary response
func (m *ServerSummaryResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServerSummaryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerSummaryResponse) UnmarshalBinary(b []byte) error {
	var res ServerSummaryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
