// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SummaryMetricThresholdResponse SummaryMetricThresholdResponse
// swagger:model SummaryMetricThresholdResponse
type SummaryMetricThresholdResponse struct {

	// caution
	Caution float64 `json:"caution,omitempty"`

	// critical
	Critical float64 `json:"critical,omitempty"`
}

// Validate validates this summary metric threshold response
func (m *SummaryMetricThresholdResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SummaryMetricThresholdResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SummaryMetricThresholdResponse) UnmarshalBinary(b []byte) error {
	var res SummaryMetricThresholdResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
