// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SyntheticsCondition SyntheticsCondition
// swagger:model SyntheticsCondition
type SyntheticsCondition struct {

	// synthetics condition
	SyntheticsCondition *SyntheticsConditionBody `json:"synthetics_condition,omitempty"`
}

// Validate validates this synthetics condition
func (m *SyntheticsCondition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSyntheticsCondition(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SyntheticsCondition) validateSyntheticsCondition(formats strfmt.Registry) error {

	if swag.IsZero(m.SyntheticsCondition) { // not required
		return nil
	}

	if m.SyntheticsCondition != nil {
		if err := m.SyntheticsCondition.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("synthetics_condition")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SyntheticsCondition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SyntheticsCondition) UnmarshalBinary(b []byte) error {
	var res SyntheticsCondition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
