// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// UserDefinedConditionBody UserDefinedConditionBody
// swagger:model UserDefinedConditionBody
type UserDefinedConditionBody struct {

	// metric
	Metric string `json:"metric,omitempty"`

	// value function
	ValueFunction string `json:"value_function,omitempty"`
}

// Validate validates this user defined condition body
func (m *UserDefinedConditionBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserDefinedConditionBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserDefinedConditionBody) UnmarshalBinary(b []byte) error {
	var res UserDefinedConditionBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
