// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ViolationEntityResponse ViolationEntityResponse
// swagger:model ViolationEntityResponse
type ViolationEntityResponse struct {

	// group id
	GroupID int32 `json:"group_id,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// product
	Product string `json:"product,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this violation entity response
func (m *ViolationEntityResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ViolationEntityResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ViolationEntityResponse) UnmarshalBinary(b []byte) error {
	var res ViolationEntityResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
