// Code generated by go-swagger; DO NOT EDIT.

package labels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/burck1/go-newrelic/models"
)

// V2LabelsJSONByKeyDeleteReader is a Reader for the V2LabelsJSONByKeyDelete structure.
type V2LabelsJSONByKeyDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2LabelsJSONByKeyDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewV2LabelsJSONByKeyDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewV2LabelsJSONByKeyDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewV2LabelsJSONByKeyDeleteForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewV2LabelsJSONByKeyDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV2LabelsJSONByKeyDeleteOK creates a V2LabelsJSONByKeyDeleteOK with default headers values
func NewV2LabelsJSONByKeyDeleteOK() *V2LabelsJSONByKeyDeleteOK {
	return &V2LabelsJSONByKeyDeleteOK{}
}

/*V2LabelsJSONByKeyDeleteOK handles this case with default header values.

OK
*/
type V2LabelsJSONByKeyDeleteOK struct {
	Payload *models.LabelResponse
}

func (o *V2LabelsJSONByKeyDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /v2/labels/{key}.json][%d] v2LabelsJsonByKeyDeleteOK  %+v", 200, o.Payload)
}

func (o *V2LabelsJSONByKeyDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LabelResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2LabelsJSONByKeyDeleteUnauthorized creates a V2LabelsJSONByKeyDeleteUnauthorized with default headers values
func NewV2LabelsJSONByKeyDeleteUnauthorized() *V2LabelsJSONByKeyDeleteUnauthorized {
	return &V2LabelsJSONByKeyDeleteUnauthorized{}
}

/*V2LabelsJSONByKeyDeleteUnauthorized handles this case with default header values.

Invalid API key
*/
type V2LabelsJSONByKeyDeleteUnauthorized struct {
	Payload interface{}
}

func (o *V2LabelsJSONByKeyDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v2/labels/{key}.json][%d] v2LabelsJsonByKeyDeleteUnauthorized  %+v", 401, o.Payload)
}

func (o *V2LabelsJSONByKeyDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2LabelsJSONByKeyDeleteForbidden creates a V2LabelsJSONByKeyDeleteForbidden with default headers values
func NewV2LabelsJSONByKeyDeleteForbidden() *V2LabelsJSONByKeyDeleteForbidden {
	return &V2LabelsJSONByKeyDeleteForbidden{}
}

/*V2LabelsJSONByKeyDeleteForbidden handles this case with default header values.

New Relic API access has not been enabled
*/
type V2LabelsJSONByKeyDeleteForbidden struct {
	Payload interface{}
}

func (o *V2LabelsJSONByKeyDeleteForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v2/labels/{key}.json][%d] v2LabelsJsonByKeyDeleteForbidden  %+v", 403, o.Payload)
}

func (o *V2LabelsJSONByKeyDeleteForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2LabelsJSONByKeyDeleteDefault creates a V2LabelsJSONByKeyDeleteDefault with default headers values
func NewV2LabelsJSONByKeyDeleteDefault(code int) *V2LabelsJSONByKeyDeleteDefault {
	return &V2LabelsJSONByKeyDeleteDefault{
		_statusCode: code,
	}
}

/*V2LabelsJSONByKeyDeleteDefault handles this case with default header values.

A server error occurred, please contact <a href="http://support.newrelic.com">New Relic support</a>
*/
type V2LabelsJSONByKeyDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the v2 labels Json by key delete default response
func (o *V2LabelsJSONByKeyDeleteDefault) Code() int {
	return o._statusCode
}

func (o *V2LabelsJSONByKeyDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /v2/labels/{key}.json][%d] V2LabelsJsonByKeyDelete default  %+v", o._statusCode, o.Payload)
}

func (o *V2LabelsJSONByKeyDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
